CREATE FUNCTION getNthHighestSalary(N INT)
RETURNS INT
BEGIN
DECLARE RESULT INT;
SELECT IF(COUNT(A.SALARY) = N,MIN(A.SALARY),NULL) INTO RESULT
    FROM (
        SELECT DISTINCT SALARY FROM EMPLOYEE
        ORDER BY SALARY DESC
        LIMIT N
    )A;
RETURN RESULT;
END