CREATE FUNCTION getNthHighestSalary(N INT) RETURNS INT
BEGIN
DECLARE RESULT INT;
SET N = N-1;
(SELECT DISTINCT SALARY INTO RESULT
        FROM EMPLOYEE
        ORDER BY SALARY DESC
        LIMIT 1 OFFSET N
  );
RETURN RESULT;
END
