-- -- -- -- -- -- -- -- -- -- -- -- -- # Write your MySQL query statement below
-- -- -- -- -- -- -- -- -- -- -- -- -- with base as (
-- -- -- -- -- -- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- -- -- -- -- -- --         distinct
-- -- -- -- -- -- -- -- -- -- -- -- --         date_format(a.pay_date,'%Y-%m') as pay_month,
-- -- -- -- -- -- -- -- -- -- -- -- --         b.department_id,
-- -- -- -- -- -- -- -- -- -- -- -- --         avg(a.amount) over (partition by date_format(a.pay_date,'%Y-%m'),b.department_id) as dept_avg,
-- -- -- -- -- -- -- -- -- -- -- -- --         avg(a.amount) over (partition by date_format(a.pay_date,'%Y-%m')) as total_avg
-- -- -- -- -- -- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- -- -- -- -- -- --         Salary a
-- -- -- -- -- -- -- -- -- -- -- -- --     inner join 
-- -- -- -- -- -- -- -- -- -- -- -- --         Employee b 
-- -- -- -- -- -- -- -- -- -- -- -- --     on 
-- -- -- -- -- -- -- -- -- -- -- -- --         a.employee_id = b.employee_id
-- -- -- -- -- -- -- -- -- -- -- -- -- )
-- -- -- -- -- -- -- -- -- -- -- -- -- select 
-- -- -- -- -- -- -- -- -- -- -- -- --     distinct
-- -- -- -- -- -- -- -- -- -- -- -- --     pay_month,
-- -- -- -- -- -- -- -- -- -- -- -- --     department_id,
-- -- -- -- -- -- -- -- -- -- -- -- --     case when total_avg < dept_avg then 'higher'
-- -- -- -- -- -- -- -- -- -- -- -- --         when total_avg > dept_avg then 'lower'
-- -- -- -- -- -- -- -- -- -- -- -- --         else 'same' end as comparison
-- -- -- -- -- -- -- -- -- -- -- -- -- from
-- -- -- -- -- -- -- -- -- -- -- -- --     base 
-- -- -- -- -- -- -- -- -- -- -- -- with base as (
-- -- -- -- -- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- -- -- -- -- --         date_format(b.pay_date,'%Y-%m') as pay_month,
-- -- -- -- -- -- -- -- -- -- -- --         a.employee_id,
-- -- -- -- -- -- -- -- -- -- -- --         a.department_id,
-- -- -- -- -- -- -- -- -- -- -- --         b.amount
-- -- -- -- -- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- -- -- -- -- --         Employee a
-- -- -- -- -- -- -- -- -- -- -- --     inner join 
-- -- -- -- -- -- -- -- -- -- -- --         Salary b 
-- -- -- -- -- -- -- -- -- -- -- --     on 
-- -- -- -- -- -- -- -- -- -- -- --         a.employee_id = b.employee_id
-- -- -- -- -- -- -- -- -- -- -- -- )
-- -- -- -- -- -- -- -- -- -- -- -- select 
-- -- -- -- -- -- -- -- -- -- -- --     distinct
-- -- -- -- -- -- -- -- -- -- -- --     pay_month,
-- -- -- -- -- -- -- -- -- -- -- --     department_id,
-- -- -- -- -- -- -- -- -- -- -- --     case when dept_avg > company_avg then 'higher'
-- -- -- -- -- -- -- -- -- -- -- --         when dept_avg = company_avg then 'same'
-- -- -- -- -- -- -- -- -- -- -- --         else 'lower' end as comparison
-- -- -- -- -- -- -- -- -- -- -- -- from (
-- -- -- -- -- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- -- -- -- -- --         pay_month,
-- -- -- -- -- -- -- -- -- -- -- --         department_id,
-- -- -- -- -- -- -- -- -- -- -- --         avg(amount) over (partition by pay_month,department_id) as dept_avg,
-- -- -- -- -- -- -- -- -- -- -- --         avg(amount) over (partition by pay_month) as company_avg
-- -- -- -- -- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- -- -- -- -- --         base 
-- -- -- -- -- -- -- -- -- -- -- -- ) a
-- -- -- -- -- -- -- -- -- -- -- with base as (
-- -- -- -- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- -- -- -- --         date_format(pay_date,'%Y-%m') as month,
-- -- -- -- -- -- -- -- -- -- --         avg(amount) as avg_sal
-- -- -- -- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- -- -- -- --         Salary
-- -- -- -- -- -- -- -- -- -- --     group by 
-- -- -- -- -- -- -- -- -- -- --         month
-- -- -- -- -- -- -- -- -- -- -- ),
-- -- -- -- -- -- -- -- -- -- -- dept_avg as (
-- -- -- -- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- -- -- -- --         date_format(a.pay_date,'%Y-%m') as month,
-- -- -- -- -- -- -- -- -- -- --         b.department_id,
-- -- -- -- -- -- -- -- -- -- --         avg(a.amount) as dept_avg_sal
-- -- -- -- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- -- -- -- --         Salary a
-- -- -- -- -- -- -- -- -- -- --     inner join 
-- -- -- -- -- -- -- -- -- -- --         Employee b
-- -- -- -- -- -- -- -- -- -- --     on 
-- -- -- -- -- -- -- -- -- -- --         a.employee_id = b.employee_id
-- -- -- -- -- -- -- -- -- -- --     group by 
-- -- -- -- -- -- -- -- -- -- --         month, b.department_id
-- -- -- -- -- -- -- -- -- -- -- )
-- -- -- -- -- -- -- -- -- -- -- select 
-- -- -- -- -- -- -- -- -- -- --     a.month as pay_month,
-- -- -- -- -- -- -- -- -- -- --     a.department_id,
-- -- -- -- -- -- -- -- -- -- --     case when a.dept_avg_sal > b.avg_sal then 'higher' 
-- -- -- -- -- -- -- -- -- -- --         when a.dept_avg_sal = b.avg_sal then 'same'
-- -- -- -- -- -- -- -- -- -- --         else 'lower' end as comparison
-- -- -- -- -- -- -- -- -- -- -- from 
-- -- -- -- -- -- -- -- -- -- --     dept_avg a 
-- -- -- -- -- -- -- -- -- -- -- inner join 
-- -- -- -- -- -- -- -- -- -- --     base b 
-- -- -- -- -- -- -- -- -- -- -- on 
-- -- -- -- -- -- -- -- -- -- --     a.month = b.month
-- -- -- -- -- -- -- -- -- -- with base as (
-- -- -- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- -- -- --         date_format(b.pay_date,'%Y-%m') as pay_month,
-- -- -- -- -- -- -- -- -- --         a.employee_id,
-- -- -- -- -- -- -- -- -- --         a.department_id,
-- -- -- -- -- -- -- -- -- --         sum(b.amount) as amount
-- -- -- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- -- -- --         Employee a 
-- -- -- -- -- -- -- -- -- --     inner join 
-- -- -- -- -- -- -- -- -- --         Salary b 
-- -- -- -- -- -- -- -- -- --     on 
-- -- -- -- -- -- -- -- -- --         a.employee_id = b.employee_id
-- -- -- -- -- -- -- -- -- --     group by 
-- -- -- -- -- -- -- -- -- --         pay_month, a.employee_id, a.department_id
-- -- -- -- -- -- -- -- -- -- ),
-- -- -- -- -- -- -- -- -- -- final_info as (
-- -- -- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- -- -- --         pay_month,
-- -- -- -- -- -- -- -- -- --         employee_id,
-- -- -- -- -- -- -- -- -- --         department_id,
-- -- -- -- -- -- -- -- -- --         avg(amount) over (partition by pay_month,department_id) as dept_avg,
-- -- -- -- -- -- -- -- -- --         avg(amount) over (partition by pay_month) as company_avg
-- -- -- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- -- -- --         base
-- -- -- -- -- -- -- -- -- -- )
-- -- -- -- -- -- -- -- -- -- select 
-- -- -- -- -- -- -- -- -- --     distinct
-- -- -- -- -- -- -- -- -- --     pay_month,
-- -- -- -- -- -- -- -- -- --     department_id,
-- -- -- -- -- -- -- -- -- --     case when dept_avg > company_avg then 'higher'
-- -- -- -- -- -- -- -- -- --     when dept_avg = company_avg then 'same'
-- -- -- -- -- -- -- -- -- --     else 'lower' end as comparison
-- -- -- -- -- -- -- -- -- -- from 
-- -- -- -- -- -- -- -- -- --     final_info
-- -- -- -- -- -- -- -- -- with base as (
-- -- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- -- --         date_format(a.pay_date,'%Y-%m') as pay_month,
-- -- -- -- -- -- -- -- --         b.department_id,
-- -- -- -- -- -- -- -- --         a.employee_id,
-- -- -- -- -- -- -- -- --         sum(a.amount) as amount
-- -- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- -- --         Salary a 
-- -- -- -- -- -- -- -- --     inner join 
-- -- -- -- -- -- -- -- --         Employee b 
-- -- -- -- -- -- -- -- --     on 
-- -- -- -- -- -- -- -- --         a.employee_id = b.employee_id 
-- -- -- -- -- -- -- -- --     group by 
-- -- -- -- -- -- -- -- --         pay_month,b.department_id,a.employee_id
-- -- -- -- -- -- -- -- -- )
-- -- -- -- -- -- -- -- -- select 
-- -- -- -- -- -- -- -- --     distinct 
-- -- -- -- -- -- -- -- --     pay_month,
-- -- -- -- -- -- -- -- --     department_id,
-- -- -- -- -- -- -- -- --     case when dept_avg > company_avg then 'higher'
-- -- -- -- -- -- -- -- --         when dept_avg = company_avg then 'same'
-- -- -- -- -- -- -- -- --         else 'lower' end as comparison
-- -- -- -- -- -- -- -- -- from (
-- -- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- -- --         pay_month,
-- -- -- -- -- -- -- -- --         department_id,
-- -- -- -- -- -- -- -- --         avg(amount) over (partition by pay_month,department_id) as dept_avg,
-- -- -- -- -- -- -- -- --         avg(amount) over (partition by pay_month) as company_avg
-- -- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- -- --         base 
-- -- -- -- -- -- -- -- -- ) a
-- -- -- -- -- -- -- -- with base as (
-- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- --         date_format(a.pay_date,'%Y-%m') as pay_month,
-- -- -- -- -- -- -- --         b.department_id,
-- -- -- -- -- -- -- --         avg(a.amount) over (partition by date_format(a.pay_date,'%Y-%m'),b.department_id) as team_avg,
-- -- -- -- -- -- -- --         avg(a.amount) over (partition by date_format(a.pay_date,'%Y-%m')) as company_avg
-- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- --         Salary a 
-- -- -- -- -- -- -- --     inner join
-- -- -- -- -- -- -- --         Employee b 
-- -- -- -- -- -- -- --     on 
-- -- -- -- -- -- -- --         a.employee_id = b.employee_id
-- -- -- -- -- -- -- -- )
-- -- -- -- -- -- -- -- select 
-- -- -- -- -- -- -- --     distinct
-- -- -- -- -- -- -- --     pay_month,
-- -- -- -- -- -- -- --     department_id,
-- -- -- -- -- -- -- --     case when team_avg > company_avg then 'higher' 
-- -- -- -- -- -- -- --         when team_avg = company_avg then 'same'
-- -- -- -- -- -- -- --         else 'lower' end as comparison
-- -- -- -- -- -- -- -- from 
-- -- -- -- -- -- -- --     base 
-- -- -- -- -- -- -- with base as (
-- -- -- -- -- -- --     select 
-- -- -- -- -- -- --         distinct
-- -- -- -- -- -- --         date_format(a.pay_date, '%Y-%m') as pay_month,
-- -- -- -- -- -- --         b.department_id,
-- -- -- -- -- -- --         avg(amount) over (partition by date_format(a.pay_date,'%Y-%m'),b.department_id) as dept_avg,
-- -- -- -- -- -- --         avg(amount) over (partition by date_format(a.pay_date,'%Y-%m')) as company_avg
-- -- -- -- -- -- --     from 
-- -- -- -- -- -- --         Salary a 
-- -- -- -- -- -- --     inner join 
-- -- -- -- -- -- --         Employee b 
-- -- -- -- -- -- --     on 
-- -- -- -- -- -- --         a.employee_id = b.employee_id 
-- -- -- -- -- -- -- )
-- -- -- -- -- -- -- select 
-- -- -- -- -- -- --     pay_month,
-- -- -- -- -- -- --     department_id,
-- -- -- -- -- -- --     case when dept_avg > company_avg then 'higher'
-- -- -- -- -- -- --         when dept_avg = company_avg then 'same'
-- -- -- -- -- -- --         else 'lower' end as comparison
-- -- -- -- -- -- -- from 
-- -- -- -- -- -- --     base 
-- -- -- -- -- -- with base as (
-- -- -- -- -- --     select 
-- -- -- -- -- --         date_format(s.pay_date,'%Y-%m') as pay_month,
-- -- -- -- -- --         e.department_id as department_id,
-- -- -- -- -- --         avg(s.amount) over (partition by date_format(s.pay_date,'%Y-%m'),e.department_id) as dept_avg,
-- -- -- -- -- --         avg(s.amount) over (partition by date_format(s.pay_date,'%Y-%m')) as company_avg
-- -- -- -- -- --     from 
-- -- -- -- -- --         Employee e 
-- -- -- -- -- --     inner join 
-- -- -- -- -- --         Salary s 
-- -- -- -- -- --     on 
-- -- -- -- -- --         e.employee_id = s.employee_id
-- -- -- -- -- -- )
-- -- -- -- -- -- select 
-- -- -- -- -- --     distinct
-- -- -- -- -- --     pay_month,
-- -- -- -- -- --     department_id,
-- -- -- -- -- --     case when company_avg > dept_avg then 'lower'
-- -- -- -- -- --         when company_avg = dept_avg then 'same'
-- -- -- -- -- --         else 'higher' end as comparison
-- -- -- -- -- -- from 
-- -- -- -- -- --     base 
-- -- -- -- -- with base as (
-- -- -- -- --     select 
-- -- -- -- --         date_format(a.pay_date,'%Y-%m') as pay_month,
-- -- -- -- --         b.department_id,
-- -- -- -- --         a.amount
-- -- -- -- --     from
-- -- -- -- --         Salary a 
-- -- -- -- --     inner join 
-- -- -- -- --         Employee b 
-- -- -- -- --     on 
-- -- -- -- --         a.employee_id = b.employee_id
-- -- -- -- -- )
-- -- -- -- -- select
-- -- -- -- --     distinct 
-- -- -- -- --     pay_month,
-- -- -- -- --     department_id,
-- -- -- -- --     case when dept_avg > company_avg then 'higher'
-- -- -- -- --         when dept_avg = company_avg then 'same'
-- -- -- -- --         else 'lower' end as comparison 
-- -- -- -- -- from (
-- -- -- -- --     select 
-- -- -- -- --         pay_month,
-- -- -- -- --         department_id,
-- -- -- -- --         avg(amount) over (partition by pay_month,department_id) as dept_avg,
-- -- -- -- --         avg(amount) over (partition by pay_month) as company_avg 
-- -- -- -- --     from 
-- -- -- -- --         base 
-- -- -- -- -- ) a 
-- -- -- -- with base as (
-- -- -- --     select 
-- -- -- --         distinct
-- -- -- --         date_format(a.pay_date,'%Y-%m') as pay_month,
-- -- -- --         b.department_id,
-- -- -- --         avg(a.amount) over (partition by date_format(a.pay_date,'%Y-%m'),b.department_id) as dept_avg,
-- -- -- --         avg(a.amount) over (partition by date_format(a.pay_date,'%Y-%m')) as company_avg 
-- -- -- --     from 
-- -- -- --         Salary a 
-- -- -- --     inner join 
-- -- -- --         Employee b 
-- -- -- --     on 
-- -- -- --         a.employee_id = b.employee_id 
-- -- -- -- )
-- -- -- -- select 
-- -- -- --     pay_month,
-- -- -- --     department_id,
-- -- -- --     case when dept_avg > company_avg then 'higher'
-- -- -- --         when dept_avg = company_avg then 'same'
-- -- -- --             else 'lower' end as comparison
-- -- -- -- from 
-- -- -- --     base 
-- -- -- with base as (
-- -- --     select 
-- -- --         distinct 
-- -- --         date_format(a.pay_date,'%Y-%m') as pay_month,
-- -- --         b.department_id,
-- -- --         avg(amount) over (partition by date_format(a.pay_date,'%Y-%m'),b.department_id) as dept_avg,
-- -- --         avg(amount) over (partition by date_format(a.pay_date,'%Y-%m')) as company_avg 
-- -- --     from 
-- -- --         Salary a 
-- -- --     inner join 
-- -- --         Employee b 
-- -- --     on 
-- -- --         a.employee_id = b.employee_id 
-- -- -- )
-- -- -- select 
-- -- --     pay_month,
-- -- --     department_id,
-- -- --     case when dept_avg > company_avg then 'higher'
-- -- --         when dept_avg = company_avg then 'same' 
-- -- --             else 'lower' end as comparison
-- -- -- from 
-- -- --     base 
-- -- select 
-- --     pay_month,
-- --     department_id,
-- --     case when dept_avg > company_avg then 'higher'
-- --         when dept_avg < company_avg then 'lower' else 'same' end as comparison
-- -- from (
-- --     select 
-- --         distinct
-- --         date_format(a.pay_date,'%Y-%m') as pay_month,
-- --         b.department_id,
-- --         avg(a.amount) over (partition by date_format(a.pay_date,'%Y-%m')) as company_avg,
-- --         avg(a.amount) over (partition by date_format(a.pay_date,'%Y-%m'),b.department_id) as dept_avg
-- --     from 
-- --         Salary a 
-- --     inner join 
-- --         Employee b 
-- --     on 
-- --         a.employee_id = b.employee_id 
-- -- ) a 
-- with base as (
--     select 
--         date_format(b.pay_date,'%Y-%m') as pay_month,
--         a.department_id,
--         avg(b.amount) over (partition by date_format(b.pay_date,'%Y-%m'),a.department_id) as dept_avg,
--         avg(b.amount) over (partition by date_format(b.pay_date,'%Y-%m')) as company_avg
--     from 
--         Employee a 
--     inner join 
--         Salary b 
--     on 
--         a.employee_id = b.employee_id 
-- )
-- select 
--     pay_month,
--     department_id,
--     max(case when dept_avg > company_avg then 'higher'
--         when dept_avg < company_avg then 'lower' else 'same' end) as comparison
-- from 
--     base 
-- group by 
--     pay_month, department_id 
select 
    pay_month,
    department_id,
    max(case when dept_avg > company_avg then 'higher'
        when dept_avg < company_avg then 'lower' else 'same' end) as comparison
from ( 
    select 
        date_format(a.pay_date,'%Y-%m') as pay_month,
        b.department_id,
        avg(a.amount) over (partition by b.department_id,date_format(a.pay_date,'%Y-%m')) as dept_avg,
        avg(a.amount) over (partition by date_format(a.pay_date,'%Y-%m')) as company_avg
    from 
        Salary a 
    inner join 
        Employee b 
    on 
        a.employee_id = b.employee_id
) a 
group by 
    pay_month, department_id