-- -- -- -- -- -- -- -- -- -- -- -- # Write your MySQL query statement below
-- -- -- -- -- -- -- -- -- -- -- -- with base as (
-- -- -- -- -- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- -- -- -- -- --         first_player as player,
-- -- -- -- -- -- -- -- -- -- -- --         first_score as score
-- -- -- -- -- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- -- -- -- -- --         Matches
-- -- -- -- -- -- -- -- -- -- -- --     union all
-- -- -- -- -- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- -- -- -- -- --         second_player as player,
-- -- -- -- -- -- -- -- -- -- -- --         second_score as score
-- -- -- -- -- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- -- -- -- -- --         Matches
-- -- -- -- -- -- -- -- -- -- -- -- ),
-- -- -- -- -- -- -- -- -- -- -- -- players_scores as (
-- -- -- -- -- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- -- -- -- -- --         distinct
-- -- -- -- -- -- -- -- -- -- -- --         a.player_id,
-- -- -- -- -- -- -- -- -- -- -- --         a.group_id,
-- -- -- -- -- -- -- -- -- -- -- --         sum(b.score) over (partition by a.player_id) as score
-- -- -- -- -- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- -- -- -- -- --         Players a
-- -- -- -- -- -- -- -- -- -- -- --     inner join
-- -- -- -- -- -- -- -- -- -- -- --         base b
-- -- -- -- -- -- -- -- -- -- -- --     on 
-- -- -- -- -- -- -- -- -- -- -- --         a.player_id = b.player
-- -- -- -- -- -- -- -- -- -- -- -- )
-- -- -- -- -- -- -- -- -- -- -- -- select
-- -- -- -- -- -- -- -- -- -- -- --     a.group_id,
-- -- -- -- -- -- -- -- -- -- -- --     a.player_id
-- -- -- -- -- -- -- -- -- -- -- -- from (    
-- -- -- -- -- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- -- -- -- -- --         distinct
-- -- -- -- -- -- -- -- -- -- -- --         player_id,
-- -- -- -- -- -- -- -- -- -- -- --         group_id,
-- -- -- -- -- -- -- -- -- -- -- --         dense_rank() over (partition by group_id order by score desc, player_id asc) as grp_score_ranks
-- -- -- -- -- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- -- -- -- -- --         players_scores
-- -- -- -- -- -- -- -- -- -- -- -- ) a
-- -- -- -- -- -- -- -- -- -- -- -- where 
-- -- -- -- -- -- -- -- -- -- -- --     a.grp_score_ranks = 1

-- -- -- -- -- -- -- -- -- -- -- with base as (
-- -- -- -- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- -- -- -- --         first_player,
-- -- -- -- -- -- -- -- -- -- --         second_player,
-- -- -- -- -- -- -- -- -- -- --         first_score,
-- -- -- -- -- -- -- -- -- -- --         second_score
-- -- -- -- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- -- -- -- --         Matches
-- -- -- -- -- -- -- -- -- -- --     union all
-- -- -- -- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- -- -- -- --         second_player,
-- -- -- -- -- -- -- -- -- -- --         first_player,
-- -- -- -- -- -- -- -- -- -- --         second_score,
-- -- -- -- -- -- -- -- -- -- --         first_score
-- -- -- -- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- -- -- -- --         Matches
-- -- -- -- -- -- -- -- -- -- -- ),
-- -- -- -- -- -- -- -- -- -- -- sum_score as (
-- -- -- -- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- -- -- -- --         first_player as player,
-- -- -- -- -- -- -- -- -- -- --         sum(first_score) as score
-- -- -- -- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- -- -- -- --         base
-- -- -- -- -- -- -- -- -- -- --     group by 
-- -- -- -- -- -- -- -- -- -- --         player
-- -- -- -- -- -- -- -- -- -- -- )
-- -- -- -- -- -- -- -- -- -- -- select 
-- -- -- -- -- -- -- -- -- -- --     distinct
-- -- -- -- -- -- -- -- -- -- --     group_id as GROUP_ID,
-- -- -- -- -- -- -- -- -- -- --     player_id as PLAYER_ID
-- -- -- -- -- -- -- -- -- -- -- from (
-- -- -- -- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- -- -- -- --         a.player_id,
-- -- -- -- -- -- -- -- -- -- --         a.group_id,
-- -- -- -- -- -- -- -- -- -- --         dense_rank() over (partition by a.group_id order by ifnull(b.score,0) desc, a.player_id asc) as ranks
-- -- -- -- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- -- -- -- --         Players a 
-- -- -- -- -- -- -- -- -- -- --     left join 
-- -- -- -- -- -- -- -- -- -- --         sum_score b
-- -- -- -- -- -- -- -- -- -- --     on 
-- -- -- -- -- -- -- -- -- -- --         a.player_id = b.player
-- -- -- -- -- -- -- -- -- -- -- ) a
-- -- -- -- -- -- -- -- -- -- -- where 
-- -- -- -- -- -- -- -- -- -- --     ranks = 1
-- -- -- -- -- -- -- -- -- -- with base as (
-- -- -- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- -- -- --         a.player_id,
-- -- -- -- -- -- -- -- -- --         a.group_id,
-- -- -- -- -- -- -- -- -- --         ifnull(b.first_score,0) as score
-- -- -- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- -- -- --         Players a 
-- -- -- -- -- -- -- -- -- --     left join
-- -- -- -- -- -- -- -- -- --         Matches b 
-- -- -- -- -- -- -- -- -- --     on 
-- -- -- -- -- -- -- -- -- --         a.player_id = b.first_player
-- -- -- -- -- -- -- -- -- --     union all
-- -- -- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- -- -- --         a.player_id,
-- -- -- -- -- -- -- -- -- --         a.group_id,
-- -- -- -- -- -- -- -- -- --         ifnull(b.second_score,0) as score
-- -- -- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- -- -- --         Players a
-- -- -- -- -- -- -- -- -- --     left join 
-- -- -- -- -- -- -- -- -- --         Matches b 
-- -- -- -- -- -- -- -- -- --     on 
-- -- -- -- -- -- -- -- -- --         a.player_id = b.second_player
-- -- -- -- -- -- -- -- -- -- ),
-- -- -- -- -- -- -- -- -- -- final_info as (
-- -- -- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- -- -- --         group_id,
-- -- -- -- -- -- -- -- -- --         player_id,
-- -- -- -- -- -- -- -- -- --         dense_rank() over (partition by group_id order by score desc, player_id asc) as ranks
-- -- -- -- -- -- -- -- -- --     from (
-- -- -- -- -- -- -- -- -- --         select 
-- -- -- -- -- -- -- -- -- --             group_id,
-- -- -- -- -- -- -- -- -- --             player_id,
-- -- -- -- -- -- -- -- -- --             sum(score) as score
-- -- -- -- -- -- -- -- -- --         from 
-- -- -- -- -- -- -- -- -- --             base 
-- -- -- -- -- -- -- -- -- --         group by 
-- -- -- -- -- -- -- -- -- --             group_id, player_id
-- -- -- -- -- -- -- -- -- --     ) a
-- -- -- -- -- -- -- -- -- -- )
-- -- -- -- -- -- -- -- -- -- select 
-- -- -- -- -- -- -- -- -- --     group_id,
-- -- -- -- -- -- -- -- -- --     player_id
-- -- -- -- -- -- -- -- -- -- from 
-- -- -- -- -- -- -- -- -- --     final_info 
-- -- -- -- -- -- -- -- -- -- where 
-- -- -- -- -- -- -- -- -- --     ranks = 1
-- -- -- -- -- -- -- -- -- with base as (
-- -- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- -- --         a.group_id as first_group,
-- -- -- -- -- -- -- -- --         b.first_player,
-- -- -- -- -- -- -- -- --         b.second_player,
-- -- -- -- -- -- -- -- --         c.group_id as second_group,
-- -- -- -- -- -- -- -- --         b.first_score,
-- -- -- -- -- -- -- -- --         b.second_score
-- -- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- -- --         Players a 
-- -- -- -- -- -- -- -- --     inner join 
-- -- -- -- -- -- -- -- --         Matches b 
-- -- -- -- -- -- -- -- --     on 
-- -- -- -- -- -- -- -- --         a.player_id = b.first_player
-- -- -- -- -- -- -- -- --     inner join 
-- -- -- -- -- -- -- -- --         Players c 
-- -- -- -- -- -- -- -- --     on 
-- -- -- -- -- -- -- -- --         c.player_id = b.second_player
-- -- -- -- -- -- -- -- -- ),
-- -- -- -- -- -- -- -- -- final_info as (
-- -- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- -- --         first_player,
-- -- -- -- -- -- -- -- --         first_group,
-- -- -- -- -- -- -- -- --         first_score
-- -- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- -- --         base 
-- -- -- -- -- -- -- -- --     union all
-- -- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- -- --         second_player,
-- -- -- -- -- -- -- -- --         second_group,
-- -- -- -- -- -- -- -- --         second_score
-- -- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- -- --         base
-- -- -- -- -- -- -- -- -- ),
-- -- -- -- -- -- -- -- -- last_info as (
-- -- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- -- --         group_id,
-- -- -- -- -- -- -- -- --         player_id,
-- -- -- -- -- -- -- -- --         dense_rank() over (partition by group_id order by score desc, player_id asc) as ranks
-- -- -- -- -- -- -- -- --     from (
-- -- -- -- -- -- -- -- --         select
-- -- -- -- -- -- -- -- --             first_group as group_id,
-- -- -- -- -- -- -- -- --             first_player as player_id,
-- -- -- -- -- -- -- -- --             sum(first_score) as score
-- -- -- -- -- -- -- -- --         from 
-- -- -- -- -- -- -- -- --             final_info 
-- -- -- -- -- -- -- -- --         group by
-- -- -- -- -- -- -- -- --             group_id, player_id
-- -- -- -- -- -- -- -- --     ) a
-- -- -- -- -- -- -- -- -- )
-- -- -- -- -- -- -- -- -- select 
-- -- -- -- -- -- -- -- --     group_id,
-- -- -- -- -- -- -- -- --     player_id
-- -- -- -- -- -- -- -- -- from 
-- -- -- -- -- -- -- -- --     last_info
-- -- -- -- -- -- -- -- -- where 
-- -- -- -- -- -- -- -- --     ranks = 1
-- -- -- -- -- -- -- -- with base as (
-- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- --         first_player as players,
-- -- -- -- -- -- -- --         first_score as scores
-- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- --         Matches 
-- -- -- -- -- -- -- --     union all
-- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- --         second_player,
-- -- -- -- -- -- -- --         second_score
-- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- --         Matches
-- -- -- -- -- -- -- -- ),
-- -- -- -- -- -- -- -- final_info as (
-- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- --         a.player_id,
-- -- -- -- -- -- -- --         a.group_id,
-- -- -- -- -- -- -- --         b.scores
-- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- --         Players a 
-- -- -- -- -- -- -- --     inner join 
-- -- -- -- -- -- -- --         base b 
-- -- -- -- -- -- -- --     on 
-- -- -- -- -- -- -- --         a.player_id = b.players 
-- -- -- -- -- -- -- -- ),
-- -- -- -- -- -- -- -- last_info as (
-- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- --         group_id,
-- -- -- -- -- -- -- --         player_id,
-- -- -- -- -- -- -- --         dense_rank() over (partition by group_id order by sum_scores desc,player_id asc) as ranks
-- -- -- -- -- -- -- --     from (
-- -- -- -- -- -- -- --         select 
-- -- -- -- -- -- -- --             group_id,
-- -- -- -- -- -- -- --             player_id,
-- -- -- -- -- -- -- --             sum(scores) as sum_scores
-- -- -- -- -- -- -- --         from 
-- -- -- -- -- -- -- --             final_info
-- -- -- -- -- -- -- --         group by 
-- -- -- -- -- -- -- --             group_id, player_id
-- -- -- -- -- -- -- --     ) a
-- -- -- -- -- -- -- -- )
-- -- -- -- -- -- -- -- select 
-- -- -- -- -- -- -- --     group_id,
-- -- -- -- -- -- -- --     player_id
-- -- -- -- -- -- -- -- from 
-- -- -- -- -- -- -- --     last_info
-- -- -- -- -- -- -- -- where 
-- -- -- -- -- -- -- --     ranks = 1
-- -- -- -- -- -- -- with base as (
-- -- -- -- -- -- --     select 
-- -- -- -- -- -- --         first_player as player,
-- -- -- -- -- -- --         first_score as score
-- -- -- -- -- -- --     from 
-- -- -- -- -- -- --         Matches 
-- -- -- -- -- -- --     union all
-- -- -- -- -- -- --     select 
-- -- -- -- -- -- --         second_player,
-- -- -- -- -- -- --         second_score
-- -- -- -- -- -- --     from 
-- -- -- -- -- -- --         Matches
-- -- -- -- -- -- -- ),
-- -- -- -- -- -- -- final_info as (
-- -- -- -- -- -- --     select 
-- -- -- -- -- -- --         group_id,
-- -- -- -- -- -- --         player,
-- -- -- -- -- -- --         sum(score) as score
-- -- -- -- -- -- --     from (
-- -- -- -- -- -- --         select 
-- -- -- -- -- -- --             a.player,
-- -- -- -- -- -- --             b.group_id,
-- -- -- -- -- -- --             a.score
-- -- -- -- -- -- --         from 
-- -- -- -- -- -- --             base a 
-- -- -- -- -- -- --         inner join 
-- -- -- -- -- -- --             Players b
-- -- -- -- -- -- --         on 
-- -- -- -- -- -- --             a.player = b.player_id
-- -- -- -- -- -- --     ) a
-- -- -- -- -- -- --     group by 
-- -- -- -- -- -- --         group_id,player
-- -- -- -- -- -- -- )
-- -- -- -- -- -- -- select 
-- -- -- -- -- -- --     group_id,
-- -- -- -- -- -- --     player_id
-- -- -- -- -- -- -- from (
-- -- -- -- -- -- --     select 
-- -- -- -- -- -- --         group_id,
-- -- -- -- -- -- --         player as player_id,
-- -- -- -- -- -- --         dense_rank() over (partition by group_id order by score desc, player) as ranks
-- -- -- -- -- -- --     from 
-- -- -- -- -- -- --         final_info
-- -- -- -- -- -- -- ) a
-- -- -- -- -- -- -- where 
-- -- -- -- -- -- --     ranks = 1
-- -- -- -- -- -- with base as (
-- -- -- -- -- --     select 
-- -- -- -- -- --         first_player as player,
-- -- -- -- -- --         first_score as score
-- -- -- -- -- --     from 
-- -- -- -- -- --         Matches 
-- -- -- -- -- --     union all 
-- -- -- -- -- --     select 
-- -- -- -- -- --         second_player as player,
-- -- -- -- -- --         second_score as score
-- -- -- -- -- --     from 
-- -- -- -- -- --         Matches
-- -- -- -- -- -- ),
-- -- -- -- -- -- groups_cte as (
-- -- -- -- -- --     select 
-- -- -- -- -- --         b.group_id,
-- -- -- -- -- --         a.player,
-- -- -- -- -- --         sum(a.score) as sum_score
-- -- -- -- -- --     from
-- -- -- -- -- --         base a 
-- -- -- -- -- --     inner join 
-- -- -- -- -- --         Players b 
-- -- -- -- -- --     on 
-- -- -- -- -- --         a.player = b.player_id
-- -- -- -- -- --     group by 
-- -- -- -- -- --         b.group_id, a.player
-- -- -- -- -- -- )
-- -- -- -- -- -- select 
-- -- -- -- -- --     group_id,
-- -- -- -- -- --     player_id
-- -- -- -- -- -- from (
-- -- -- -- -- --     select 
-- -- -- -- -- --         group_id,
-- -- -- -- -- --         player as player_id,
-- -- -- -- -- --         dense_rank() over (partition by group_id order by sum_score desc, player asc) as ranks
-- -- -- -- -- --     from 
-- -- -- -- -- --         groups_cte
-- -- -- -- -- -- ) a
-- -- -- -- -- -- where 
-- -- -- -- -- --     ranks = 1
-- -- -- -- -- with base as (
-- -- -- -- --     select 
-- -- -- -- --         first_player as player_id,
-- -- -- -- --         first_score as score
-- -- -- -- --     from 
-- -- -- -- --         Matches
-- -- -- -- --     union all
-- -- -- -- --     select 
-- -- -- -- --         second_player,
-- -- -- -- --         second_score
-- -- -- -- --     from 
-- -- -- -- --         Matches
-- -- -- -- -- ),
-- -- -- -- -- final_info as (
-- -- -- -- --     select 
-- -- -- -- --         group_id,
-- -- -- -- --         player_id,
-- -- -- -- --         dense_rank() over (partition by group_id order by player_score desc,player_id asc) as ranks
-- -- -- -- --     from (
-- -- -- -- --         select 
-- -- -- -- --             a.player_id,
-- -- -- -- --             a.score,
-- -- -- -- --             b.group_id,
-- -- -- -- --             sum(score) over (partition by a.player_id) as player_score
-- -- -- -- --         from 
-- -- -- -- --             base a 
-- -- -- -- --         inner join 
-- -- -- -- --             Players b 
-- -- -- -- --         on 
-- -- -- -- --             a.player_id = b.player_id 
-- -- -- -- --     ) a 
-- -- -- -- -- )
-- -- -- -- -- select 
-- -- -- -- --     distinct 
-- -- -- -- --     group_id,
-- -- -- -- --     player_id
-- -- -- -- -- from 
-- -- -- -- --     final_info 
-- -- -- -- -- where 
-- -- -- -- --     ranks = 1
-- -- -- -- with base as (
-- -- -- --     select 
-- -- -- --         first_player as player,
-- -- -- --         first_score as score
-- -- -- --     from 
-- -- -- --         Matches 
-- -- -- --     union all
-- -- -- --     select 
-- -- -- --         second_player,
-- -- -- --         second_score
-- -- -- --     from 
-- -- -- --         Matches
-- -- -- -- ),
-- -- -- -- final_info as (
-- -- -- --     select 
-- -- -- --         group_id,
-- -- -- --         player,
-- -- -- --         dense_rank() over (partition by group_id order by score desc, player asc) as ranks
-- -- -- --     from (
-- -- -- --         select 
-- -- -- --             b.group_id,
-- -- -- --             a.player,
-- -- -- --             sum(a.score) as score
-- -- -- --         from 
-- -- -- --             base a 
-- -- -- --         inner join 
-- -- -- --             players b 
-- -- -- --         on 
-- -- -- --             a.player = b.player_id 
-- -- -- --         group by 
-- -- -- --             b.group_id, a.player
-- -- -- --     ) a 
-- -- -- -- )
-- -- -- -- select 
-- -- -- --     group_id,
-- -- -- --     player as player_id 
-- -- -- -- from 
-- -- -- --     final_info 
-- -- -- -- where 
-- -- -- --     ranks = 1
-- -- -- with pairs as (
-- -- --     select 
-- -- --         first_player as player_id,
-- -- --         first_score as score
-- -- --     from 
-- -- --         Matches 
-- -- --     union all 
-- -- --     select 
-- -- --         second_player as player_id,
-- -- --         second_score as score
-- -- --     from 
-- -- --         Matches
-- -- -- ),
-- -- -- final_info as (
-- -- --     select 
-- -- --         a.player_id,
-- -- --         b.group_id,
-- -- --         sum(a.score) as score 
-- -- --     from 
-- -- --         pairs a
-- -- --     inner join 
-- -- --         Players b 
-- -- --     on 
-- -- --         a.player_id = b.player_id
-- -- --     group by 
-- -- --         a.player_id, b.group_id
-- -- -- )
-- -- -- select 
-- -- --     player_id,
-- -- --     group_id
-- -- -- from (
-- -- --     select 
-- -- --         player_id,
-- -- --         group_id,
-- -- --         dense_rank() over (partition by group_id order by score desc, player_id asc) as ranks 
-- -- --     from 
-- -- --         final_info 
-- -- -- ) a 
-- -- -- where 
-- -- --     ranks = 1 

-- -- with base as (
-- --     select 
-- --         first_player as player,
-- --         first_score as score
-- --     from 
-- --         Matches 
-- --     union all
-- --     select 
-- --         second_player,
-- --         second_score
-- --     from 
-- --         Matches
-- -- ),
-- -- final_info as (
-- --     select 
-- --         player as player_id,
-- --         group_id,
-- --         dense_rank() over (partition by group_id order by score desc, player) as ranks
-- --     from (
-- --         select 
-- --             a.player,
-- --             b.group_id,
-- --             sum(a.score) as score
-- --         from 
-- --             base a 
-- --         inner join 
-- --             Players b 
-- --         on 
-- --             a.player = b.player_id
-- --         group by 
-- --             a.player, b.group_id
-- --     ) a
-- -- )
-- -- select 
-- --     group_id,
-- --     player_id
-- -- from 
-- --     final_info 
-- -- where 
-- --     ranks = 1
-- with base as (
--     select 
--         first_player as player_id,
--         first_score as score
--     from 
--         Matches 
--     union all
--     select 
--         second_player as player_id,
--         second_score as score
--     from 
--         Matches
-- ),
-- final_info as (
--     select 
--         group_id,
--         player_id,
--         dense_rank() over (partition by group_id order by total_score desc, player_id asc) as ranks
--     from (
--         select 
--             a.player_id,
--             b.group_id,
--             sum(a.score) as total_score 
--         from 
--             base a 
--         inner join 
--             Players b 
--         on 
--             a.player_id = b.player_id
--         group by 
--             a.player_id,b.group_id 
--     ) a 
-- )
-- select 
--     group_id,
--     player_id
-- from 
--     final_info 
-- where 
--     ranks = 1 
with pairs as (
    select 
        first_player as player_id,
        first_score as score
    from 
        Matches
    union all
    select 
        second_player,
        second_score
    from 
        Matches
),
rank_info as (
    select 
        player_id,
        group_id,
        dense_rank() over (partition by group_id order by total_score desc, player_id asc) as ranks
    from (
        select 
            a.player_id,
            b.group_id,
            sum(a.score) as total_score
        from 
            pairs a 
        inner join 
            Players b 
        on 
            a.player_id = b.player_id
        group by 
            a.player_id
    ) a 
)
select 
    group_id,
    player_id
from 
    rank_info
where 
    ranks = 1