-- -- -- -- -- -- -- -- -- -- -- -- -- # Write your MySQL query statement below
-- -- -- -- -- -- -- -- -- -- -- -- -- with base as (
-- -- -- -- -- -- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- -- -- -- -- -- --         distinct
-- -- -- -- -- -- -- -- -- -- -- -- --         name,
-- -- -- -- -- -- -- -- -- -- -- -- --         continent,
-- -- -- -- -- -- -- -- -- -- -- -- --         row_number() over (partition by continent order by name asc) as rnums
-- -- -- -- -- -- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- -- -- -- -- -- --         Student
-- -- -- -- -- -- -- -- -- -- -- -- -- )
-- -- -- -- -- -- -- -- -- -- -- -- -- select 
-- -- -- -- -- -- -- -- -- -- -- -- --     a.America,
-- -- -- -- -- -- -- -- -- -- -- -- --     a.Asia,
-- -- -- -- -- -- -- -- -- -- -- -- --     a.Europe
-- -- -- -- -- -- -- -- -- -- -- -- -- from (
-- -- -- -- -- -- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- -- -- -- -- -- --         rnums,
-- -- -- -- -- -- -- -- -- -- -- -- --         max(case when continent = 'America' then name end) as America,
-- -- -- -- -- -- -- -- -- -- -- -- --         max(case when continent = 'Asia' then name end) as Asia,
-- -- -- -- -- -- -- -- -- -- -- -- --         max(case when continent = 'Europe' then name end) as Europe
-- -- -- -- -- -- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- -- -- -- -- -- --         base 
-- -- -- -- -- -- -- -- -- -- -- -- --     group by 
-- -- -- -- -- -- -- -- -- -- -- -- --         rnums
-- -- -- -- -- -- -- -- -- -- -- -- --     order by 
-- -- -- -- -- -- -- -- -- -- -- -- --         rnums asc
-- -- -- -- -- -- -- -- -- -- -- -- -- ) a

-- -- -- -- -- -- -- -- -- -- -- -- with base as (
-- -- -- -- -- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- -- -- -- -- --         row_number() over (partition by continent order by name) as rnums,
-- -- -- -- -- -- -- -- -- -- -- --         case when continent = 'America' then name else null end as America,
-- -- -- -- -- -- -- -- -- -- -- --         case when continent = 'Asia' then name else null end as Asia,
-- -- -- -- -- -- -- -- -- -- -- --         case when continent = 'Europe' then name else null end as Europe
-- -- -- -- -- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- -- -- -- -- --         Student
-- -- -- -- -- -- -- -- -- -- -- -- )
-- -- -- -- -- -- -- -- -- -- -- -- select 
-- -- -- -- -- -- -- -- -- -- -- --     max(America) as America,
-- -- -- -- -- -- -- -- -- -- -- --     max(Asia) as Asia,
-- -- -- -- -- -- -- -- -- -- -- --     max(Europe) as Europe
-- -- -- -- -- -- -- -- -- -- -- -- from 
-- -- -- -- -- -- -- -- -- -- -- --     base 
-- -- -- -- -- -- -- -- -- -- -- -- group by 
-- -- -- -- -- -- -- -- -- -- -- --     rnums
-- -- -- -- -- -- -- -- -- -- -- with base as (
-- -- -- -- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- -- -- -- --         name,
-- -- -- -- -- -- -- -- -- -- --         continent,
-- -- -- -- -- -- -- -- -- -- --         row_number() over (partition by continent order by name) as rnum
-- -- -- -- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- -- -- -- --         Student
-- -- -- -- -- -- -- -- -- -- -- )
-- -- -- -- -- -- -- -- -- -- -- select
-- -- -- -- -- -- -- -- -- -- --     max(case when continent = 'America' then name else null end) as America,
-- -- -- -- -- -- -- -- -- -- --     max(case when continent = 'Asia' then name else null end) as Asia,
-- -- -- -- -- -- -- -- -- -- --     max(case when continent = 'Europe' then name else null end) as Europe
-- -- -- -- -- -- -- -- -- -- -- from 
-- -- -- -- -- -- -- -- -- -- --     base 
-- -- -- -- -- -- -- -- -- -- -- group by 
-- -- -- -- -- -- -- -- -- -- --     rnum

-- -- -- -- -- -- -- -- -- -- select 
-- -- -- -- -- -- -- -- -- --     max(case when continent = 'America' then name else null end) as America,
-- -- -- -- -- -- -- -- -- --     max(case when continent = 'Asia' then name else null end) as Asia,
-- -- -- -- -- -- -- -- -- --     max(case when continent = 'Europe' then name else null end) as Europe
-- -- -- -- -- -- -- -- -- -- from (
-- -- -- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- -- -- --         row_number() over (partition by continent order by name) as rnums,
-- -- -- -- -- -- -- -- -- --         name,
-- -- -- -- -- -- -- -- -- --         continent
-- -- -- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- -- -- --         Student
-- -- -- -- -- -- -- -- -- -- ) a
-- -- -- -- -- -- -- -- -- -- group by 
-- -- -- -- -- -- -- -- -- --     rnums
-- -- -- -- -- -- -- -- -- with base as (
-- -- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- -- --         name,
-- -- -- -- -- -- -- -- --         continent,
-- -- -- -- -- -- -- -- --         row_number() over (partition by continent order by name) as rnums
-- -- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- -- --         Student
-- -- -- -- -- -- -- -- -- )
-- -- -- -- -- -- -- -- -- select 
-- -- -- -- -- -- -- -- --     max(case when continent = 'America' then name else null end) as America,
-- -- -- -- -- -- -- -- --     max(case when continent = 'Asia' then name else null end) as Asia,
-- -- -- -- -- -- -- -- --     max(case when continent = 'Europe' then name else null end) as Europe
-- -- -- -- -- -- -- -- -- from 
-- -- -- -- -- -- -- -- --     base 
-- -- -- -- -- -- -- -- -- group by 
-- -- -- -- -- -- -- -- --     rnums
-- -- -- -- -- -- -- -- select 
-- -- -- -- -- -- -- --     max(case when continent = 'America' then name else null end) as America,
-- -- -- -- -- -- -- --     max(case when continent = 'Asia' then name else null end) as Asia,
-- -- -- -- -- -- -- --     max(case when continent = 'Europe' then name else null end) as Europe
-- -- -- -- -- -- -- -- from (
-- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- --         name,
-- -- -- -- -- -- -- --         continent,
-- -- -- -- -- -- -- --         row_number() over (partition by continent order by name) as rnums
-- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- --         Student
-- -- -- -- -- -- -- -- ) a
-- -- -- -- -- -- -- -- group by 
-- -- -- -- -- -- -- --     rnums
-- -- -- -- -- -- -- select 
-- -- -- -- -- -- --     max(case when continent = 'America' then name else null end) as America,
-- -- -- -- -- -- --     max(case when continent = 'Asia' then name else null end) as Asia,
-- -- -- -- -- -- --     max(case when continent = 'Europe' then name else null end) as Europe
-- -- -- -- -- -- -- from (
-- -- -- -- -- -- --     select 
-- -- -- -- -- -- --         row_number() over (partition by continent order by name) as rnums,
-- -- -- -- -- -- --         name,
-- -- -- -- -- -- --         continent
-- -- -- -- -- -- --     from 
-- -- -- -- -- -- --         Student
-- -- -- -- -- -- -- ) a 
-- -- -- -- -- -- -- group by 
-- -- -- -- -- -- --     rnums
-- -- -- -- -- -- select 
-- -- -- -- -- --     max(case when continent = 'America' then name else null end) as America,
-- -- -- -- -- --     max(case when continent = 'Asia' then name else null end) as Asia,
-- -- -- -- -- --     max(case when continent = 'Europe' then name else null end) as Europe
-- -- -- -- -- -- from (
-- -- -- -- -- --     select 
-- -- -- -- -- --         name,
-- -- -- -- -- --         continent,
-- -- -- -- -- --         row_number() over (partition by continent order by name) as rnums
-- -- -- -- -- --     from 
-- -- -- -- -- --         Student
-- -- -- -- -- -- ) a 
-- -- -- -- -- -- group by 
-- -- -- -- -- --     rnums
-- -- -- -- -- select 
-- -- -- -- --     max(if(continent = 'America',name,null)) as America,
-- -- -- -- --     max(if(continent = 'Asia',name,null)) as Asia,
-- -- -- -- --     max(if(continent = 'Europe',name,null)) as Europe
-- -- -- -- -- from (
-- -- -- -- --     select 
-- -- -- -- --         row_number() over (partition by continent order by name) as rnums,
-- -- -- -- --         name,
-- -- -- -- --         continent
-- -- -- -- --     from 
-- -- -- -- --         Student
-- -- -- -- -- ) a 
-- -- -- -- -- group by 
-- -- -- -- --     rnums
-- -- -- -- with base as (
-- -- -- --     select 
-- -- -- --         continent,
-- -- -- --         name,
-- -- -- --         row_number() over (partition by continent order by name) as rnums
-- -- -- --     from 
-- -- -- --         Student
-- -- -- -- )
-- -- -- -- select 
-- -- -- --     max(case when continent = 'America' then name else null end) as America,
-- -- -- --     max(case when continent = 'Asia' then name else null end) as Asia,
-- -- -- --     max(case when continent = 'Europe' then name else null end) as Europe
-- -- -- -- from 
-- -- -- --     base 
-- -- -- -- group by 
-- -- -- --     rnums
-- -- -- with base as (
-- -- --     select 
-- -- --         name,
-- -- --         continent,
-- -- --         row_number() over (partition by continent order by name) as rnums
-- -- --     from 
-- -- --         Student
-- -- -- )
-- -- -- select 
-- -- --     max(case when continent = 'America' then name else null end) as America,
-- -- --     max(case when continent = 'Asia' then name else null end) as Asia,
-- -- --     max(case when continent = 'Europe' then name else null end) as Europe
-- -- -- from 
-- -- --     base 
-- -- -- group by 
-- -- --     rnums 
-- -- select 
-- --     max(case when continent = 'America' then name else null end) as America,
-- --     max(case when continent = 'Asia' then name else null end) as Asia,
-- --     max(case when continent = 'Europe' then name else null end) as Europe
-- -- from (
-- --     select 
-- --         row_number() over (partition by continent order by name) as rnums,
-- --         name,
-- --         continent
-- --     from 
-- --         Student
-- -- ) a 
-- -- group by 
-- --     rnums
-- select 
--     max(case when continent = 'America' then name else null end) as America,
--     max(case when continent = 'Asia' then name else null end) as Asia,
--     max(case when continent = 'Europe' then name else null end) as Europe
-- from (
--     select 
--         name,
--         continent,
--         row_number() over (partition by continent order by name) as rnums
--     from 
--         Student
-- ) a 
-- group by 
--     rnums
select 
    max(case when continent = 'America' then name else null end) as America,
    max(case when continent = 'Asia' then name else null end) as Asia,
    max(case when continent = 'Europe' then name else null end) as Europe
from (
    select 
        row_number() over (partition by continent order by name) as rnums,
        name,
        continent
    from 
        Student
) a
group by 
    rnums