-- -- -- -- -- -- -- -- -- -- -- -- -- -- # Write your MySQL query statement below
-- -- -- -- -- -- -- -- -- -- -- -- -- -- with base as (
-- -- -- -- -- -- -- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- -- -- -- -- -- -- --         distinct
-- -- -- -- -- -- -- -- -- -- -- -- -- --         player_id,
-- -- -- -- -- -- -- -- -- -- -- -- -- --         min(event_date) over (partition by player_id) as install_dt,
-- -- -- -- -- -- -- -- -- -- -- -- -- --         event_date,
-- -- -- -- -- -- -- -- -- -- -- -- -- --         count(player_id) over (partition by player_id,event_date) as cnts
-- -- -- -- -- -- -- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- -- -- -- -- -- -- --         Activity
-- -- -- -- -- -- -- -- -- -- -- -- -- -- )
-- -- -- -- -- -- -- -- -- -- -- -- -- -- ,cohort_installs as (
-- -- -- -- -- -- -- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- -- -- -- -- -- -- --         install_dt,
-- -- -- -- -- -- -- -- -- -- -- -- -- --         count(distinct player_id) as installs
-- -- -- -- -- -- -- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- -- -- -- -- -- -- --         base 
-- -- -- -- -- -- -- -- -- -- -- -- -- --     where 
-- -- -- -- -- -- -- -- -- -- -- -- -- --         event_date = install_dt    
-- -- -- -- -- -- -- -- -- -- -- -- -- --     group by 
-- -- -- -- -- -- -- -- -- -- -- -- -- --         1
-- -- -- -- -- -- -- -- -- -- -- -- -- -- )
-- -- -- -- -- -- -- -- -- -- -- -- -- -- ,consec as (
-- -- -- -- -- -- -- -- -- -- -- -- -- --     select
-- -- -- -- -- -- -- -- -- -- -- -- -- --         a.install_dt,
-- -- -- -- -- -- -- -- -- -- -- -- -- --         a.installs,
-- -- -- -- -- -- -- -- -- -- -- -- -- --         b.event_date,
-- -- -- -- -- -- -- -- -- -- -- -- -- --         if(b.player_id is null,0,1) as day1_consec
-- -- -- -- -- -- -- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- -- -- -- -- -- -- --         cohort_installs a 
-- -- -- -- -- -- -- -- -- -- -- -- -- --     left join 
-- -- -- -- -- -- -- -- -- -- -- -- -- --         base b 
-- -- -- -- -- -- -- -- -- -- -- -- -- --     on
-- -- -- -- -- -- -- -- -- -- -- -- -- --         a.install_dt = b.install_dt 
-- -- -- -- -- -- -- -- -- -- -- -- -- --         and a.install_dt + interval 1 day = b.event_date
-- -- -- -- -- -- -- -- -- -- -- -- -- -- )
-- -- -- -- -- -- -- -- -- -- -- -- -- -- select 
-- -- -- -- -- -- -- -- -- -- -- -- -- --     install_dt,
-- -- -- -- -- -- -- -- -- -- -- -- -- --     installs,
-- -- -- -- -- -- -- -- -- -- -- -- -- --     round(coalesce(sum(day1_consec)/installs,0),2) as Day1_retention
-- -- -- -- -- -- -- -- -- -- -- -- -- -- from 
-- -- -- -- -- -- -- -- -- -- -- -- -- --     consec
-- -- -- -- -- -- -- -- -- -- -- -- -- -- group by 
-- -- -- -- -- -- -- -- -- -- -- -- -- --     1,2

-- -- -- -- -- -- -- -- -- -- -- -- -- with base as (
-- -- -- -- -- -- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- -- -- -- -- -- --         player_id,
-- -- -- -- -- -- -- -- -- -- -- -- --         min(event_date) over (partition by player_id) as first_date,
-- -- -- -- -- -- -- -- -- -- -- -- --         date_add(min(event_date) over (partition by player_id), interval 1 day) as second_date,
-- -- -- -- -- -- -- -- -- -- -- -- --         event_date
-- -- -- -- -- -- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- -- -- -- -- -- --         Activity
-- -- -- -- -- -- -- -- -- -- -- -- -- )
-- -- -- -- -- -- -- -- -- -- -- -- -- select 
-- -- -- -- -- -- -- -- -- -- -- -- --     first_date as install_dt,
-- -- -- -- -- -- -- -- -- -- -- -- --     count(distinct player_id) as installs,
-- -- -- -- -- -- -- -- -- -- -- -- --     round(count(case when second_date = event_date then 1 else null end)/count(distinct player_id),2) as Day1_retention
-- -- -- -- -- -- -- -- -- -- -- -- -- from 
-- -- -- -- -- -- -- -- -- -- -- -- --     base
-- -- -- -- -- -- -- -- -- -- -- -- -- group by 
-- -- -- -- -- -- -- -- -- -- -- -- --     install_dt
-- -- -- -- -- -- -- -- -- -- -- -- with base as (
-- -- -- -- -- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- -- -- -- -- --         install_dt,
-- -- -- -- -- -- -- -- -- -- -- --         player_id,
-- -- -- -- -- -- -- -- -- -- -- --         lag(event_date) over (partition by install_dt order by event_date) as prev_event,
-- -- -- -- -- -- -- -- -- -- -- --         event_date
-- -- -- -- -- -- -- -- -- -- -- --     from (
-- -- -- -- -- -- -- -- -- -- -- --         select 
-- -- -- -- -- -- -- -- -- -- -- --             player_id,
-- -- -- -- -- -- -- -- -- -- -- --             min(event_date) over (partition by player_id) as install_dt,
-- -- -- -- -- -- -- -- -- -- -- --             event_date
-- -- -- -- -- -- -- -- -- -- -- --         from 
-- -- -- -- -- -- -- -- -- -- -- --             Activity
-- -- -- -- -- -- -- -- -- -- -- --     ) a
-- -- -- -- -- -- -- -- -- -- -- -- )
-- -- -- -- -- -- -- -- -- -- -- -- select 
-- -- -- -- -- -- -- -- -- -- -- --     install_dt,
-- -- -- -- -- -- -- -- -- -- -- --     count(distinct player_id) as installs,
-- -- -- -- -- -- -- -- -- -- -- --     round(count(case when datediff(event_date,install_dt) = 1 then player_id
-- -- -- -- -- -- -- -- -- -- -- --                 else null end)/count(distinct player_id),2) as Day1_retention
-- -- -- -- -- -- -- -- -- -- -- -- from 
-- -- -- -- -- -- -- -- -- -- -- --     base
-- -- -- -- -- -- -- -- -- -- -- -- group by 
-- -- -- -- -- -- -- -- -- -- -- --     install_dt
-- -- -- -- -- -- -- -- -- -- -- with base as (
-- -- -- -- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- -- -- -- --         distinct
-- -- -- -- -- -- -- -- -- -- --         min(event_date) over (partition by player_id) as install_dt,
-- -- -- -- -- -- -- -- -- -- --         player_id,
-- -- -- -- -- -- -- -- -- -- --         event_date
-- -- -- -- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- -- -- -- --         Activity
-- -- -- -- -- -- -- -- -- -- -- )
-- -- -- -- -- -- -- -- -- -- -- select 
-- -- -- -- -- -- -- -- -- -- --     install_dt,
-- -- -- -- -- -- -- -- -- -- --     count(distinct player_id) as installs,
-- -- -- -- -- -- -- -- -- -- --     ifnull(round(count(case when datediff(event_date,install_dt) = 1 then 1 else null end)/count(distinct player_id),2),0) as Day1_retention
-- -- -- -- -- -- -- -- -- -- -- from 
-- -- -- -- -- -- -- -- -- -- --     base 
-- -- -- -- -- -- -- -- -- -- -- group by 
-- -- -- -- -- -- -- -- -- -- --     install_dt

-- -- -- -- -- -- -- -- -- -- with installs as (
-- -- -- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- -- -- --         player_id,
-- -- -- -- -- -- -- -- -- --         min(event_date) as install_dt
-- -- -- -- -- -- -- -- -- --     from    
-- -- -- -- -- -- -- -- -- --         Activity 
-- -- -- -- -- -- -- -- -- --     group by 
-- -- -- -- -- -- -- -- -- --         player_id
-- -- -- -- -- -- -- -- -- -- )
-- -- -- -- -- -- -- -- -- -- select 
-- -- -- -- -- -- -- -- -- --     install_dt,
-- -- -- -- -- -- -- -- -- --     count(distinct player_id) as installs,
-- -- -- -- -- -- -- -- -- --     round(ifnull(count(case when datediff(event_date, install_dt) = 1 then player_id else null end)/count(distinct player_id),0),2) as Day1_retention
-- -- -- -- -- -- -- -- -- -- from (
-- -- -- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- -- -- --         a.player_id,
-- -- -- -- -- -- -- -- -- --         a.install_dt,
-- -- -- -- -- -- -- -- -- --         b.event_date
-- -- -- -- -- -- -- -- -- --     from
-- -- -- -- -- -- -- -- -- --         installs a 
-- -- -- -- -- -- -- -- -- --     inner join 
-- -- -- -- -- -- -- -- -- --         Activity b
-- -- -- -- -- -- -- -- -- --     on  
-- -- -- -- -- -- -- -- -- --         a.player_id = b.player_id
-- -- -- -- -- -- -- -- -- -- ) a
-- -- -- -- -- -- -- -- -- -- group by 
-- -- -- -- -- -- -- -- -- --     install_dt
-- -- -- -- -- -- -- -- -- with base as (
-- -- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- -- --         player_id,
-- -- -- -- -- -- -- -- --         min(event_date) as install_dt
-- -- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- -- --         Activity
-- -- -- -- -- -- -- -- --     group by 
-- -- -- -- -- -- -- -- --         player_id
-- -- -- -- -- -- -- -- -- )
-- -- -- -- -- -- -- -- -- select 
-- -- -- -- -- -- -- -- --     a.install_dt,
-- -- -- -- -- -- -- -- --     count(case when a.install_dt = b.event_date then a.player_id else null end) as installs,
-- -- -- -- -- -- -- -- --     round(count(case when date_add(a.install_dt,interval 1 day) = b.event_date then a.player_id else null end)/count(case when a.install_dt = b.event_date then a.player_id else null end),2) as Day1_retention
-- -- -- -- -- -- -- -- -- from 
-- -- -- -- -- -- -- -- --     base a 
-- -- -- -- -- -- -- -- -- inner join 
-- -- -- -- -- -- -- -- --     Activity b
-- -- -- -- -- -- -- -- -- on
-- -- -- -- -- -- -- -- --     a.player_id = b.player_id
-- -- -- -- -- -- -- -- -- group by 
-- -- -- -- -- -- -- -- --     a.install_dt
-- -- -- -- -- -- -- -- with install_dt_cte as (
-- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- --         player_id,
-- -- -- -- -- -- -- --         min(event_date) as install_dt
-- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- --         Activity
-- -- -- -- -- -- -- --     group by 
-- -- -- -- -- -- -- --         player_id
-- -- -- -- -- -- -- -- )
-- -- -- -- -- -- -- -- select 
-- -- -- -- -- -- -- --     install_dt,
-- -- -- -- -- -- -- --     count(distinct player_id) as installs,
-- -- -- -- -- -- -- --     round(ifnull(count(case when event_date = date_add(install_dt,interval 1 day) then player_id else null end)/count(distinct player_id),0),2) as Day1_retention
-- -- -- -- -- -- -- -- from (
-- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- --         a.player_id,
-- -- -- -- -- -- -- --         a.install_dt,
-- -- -- -- -- -- -- --         b.event_date
-- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- --         install_dt_cte a 
-- -- -- -- -- -- -- --     inner join 
-- -- -- -- -- -- -- --         Activity b
-- -- -- -- -- -- -- --     on
-- -- -- -- -- -- -- --         a.player_id = b.player_id
-- -- -- -- -- -- -- -- ) i
-- -- -- -- -- -- -- -- group by 
-- -- -- -- -- -- -- --     install_dt
-- -- -- -- -- -- -- with base as (
-- -- -- -- -- -- --     select 
-- -- -- -- -- -- --         player_id,
-- -- -- -- -- -- --         min(date(event_date)) as install_dt
-- -- -- -- -- -- --     from 
-- -- -- -- -- -- --         Activity
-- -- -- -- -- -- --     group by 
-- -- -- -- -- -- --         player_id
-- -- -- -- -- -- -- )
-- -- -- -- -- -- -- select 
-- -- -- -- -- -- --     b.install_dt,
-- -- -- -- -- -- --     count(distinct b.player_id) as installs,
-- -- -- -- -- -- --     round(ifnull(count(distinct case when a.event_date = date_add(b.install_dt,interval 1 day) then a.player_id else null end)/count(distinct a.player_id),0),2) as Day1_retention
-- -- -- -- -- -- -- from 
-- -- -- -- -- -- --     Activity a 
-- -- -- -- -- -- -- inner join 
-- -- -- -- -- -- --     base b 
-- -- -- -- -- -- -- on 
-- -- -- -- -- -- --     a.player_id = b.player_id
-- -- -- -- -- -- -- group by 
-- -- -- -- -- -- --     b.install_dt
-- -- -- -- -- -- select 
-- -- -- -- -- --     install_dt,
-- -- -- -- -- --     count(distinct player_id) as installs,
-- -- -- -- -- --     round(ifnull(count(case when date_add(install_dt,interval 1 day) = event_date then player_id else null end)/count(distinct player_id),0),2) as Day1_retention
-- -- -- -- -- -- from (
-- -- -- -- -- --     select 
-- -- -- -- -- --         player_id,
-- -- -- -- -- --         event_date,
-- -- -- -- -- --         min(event_date) over (partition by player_id) as install_dt
-- -- -- -- -- --     from 
-- -- -- -- -- --         Activity
-- -- -- -- -- -- ) a 
-- -- -- -- -- -- group by 
-- -- -- -- -- --     install_dt 
-- -- -- -- -- with install_cte as (
-- -- -- -- --     select 
-- -- -- -- --         min(event_date) over (partition by player_id) as install_dt,
-- -- -- -- --         player_id,
-- -- -- -- --         event_date
-- -- -- -- --     from 
-- -- -- -- --         Activity 
-- -- -- -- -- )
-- -- -- -- -- select 
-- -- -- -- --     install_dt,
-- -- -- -- --     count(distinct player_id) as installs,
-- -- -- -- --     round(ifnull(count(case when date_add(install_dt,interval 1 day) = event_date then player_id else null end)/count(player_id),0),2) as Day1_retention
-- -- -- -- -- from 
-- -- -- -- --     install_cte 
-- -- -- -- -- group by 
-- -- -- -- --     install_dt
-- -- -- -- with base as (
-- -- -- --     select 
-- -- -- --         player_id,
-- -- -- --         min(event_date) as install_dt
-- -- -- --     from 
-- -- -- --         Activity 
-- -- -- --     group by 
-- -- -- --         player_id 
-- -- -- -- )
-- -- -- -- select 
-- -- -- --     a.install_dt,
-- -- -- --     count(distinct a.player_id) as installs,
-- -- -- --     round(count(if(date_add(a.install_dt, interval 1 day) = b.event_date,a.player_id,null))/count(distinct a.player_id),2) as Day1_retention 
-- -- -- -- from 
-- -- -- --     base a 
-- -- -- -- inner join 
-- -- -- --     Activity b 
-- -- -- -- on 
-- -- -- --     a.player_id = b.player_id 
-- -- -- -- group by 
-- -- -- --     a.install_dt
-- -- -- with base as (
-- -- --     select  
-- -- --         player_id,
-- -- --         event_date,
-- -- --         min(event_date) over (partition by player_id) as install_dt
-- -- --     from 
-- -- --         Activity 
-- -- -- )
-- -- -- select 
-- -- --     install_dt,    
-- -- --     count(distinct player_id) as installs,
-- -- --     round(ifnull(count(distinct case when date_add(install_dt,interval 1 day) = event_date then player_id else null end)/count(distinct player_id),0),2) as Day1_retention 
-- -- -- from 
-- -- --     base 
-- -- -- group by 
-- -- --     install_dt 
-- -- select 
-- --     install_dt,
-- --     count(distinct player_id) as installs,
-- --     round(coalesce(count(case when date_add(install_dt,interval 1 day) = event_date then player_id else null end)/count(distinct case when event_date = install_dt then player_id else null end),0),2) as Day1_retention
-- -- from (
-- --     select 
-- --         player_id,
-- --         event_date,
-- --         min(event_date) over (partition by player_id) as install_dt
-- --     from 
-- --         Activity
-- -- ) a 
-- -- group by 
-- --     install_dt
-- select 
--     install_dt,
--     count(distinct player_id) as installs,
--     round(coalesce(count(distinct case when date_add(install_dt,interval 1 day) = event_date then player_id else null end)/count(distinct player_id),0),2) as Day1_retention
-- from (
--     select 
--         player_id,
--         event_date,
--         min(event_date) over (partition by player_id) as install_dt
--     from 
--         Activity 
-- ) a 
-- group by 
--     install_dt
with base as (
    select 
        install_dt,
        count(distinct player_id) as installs,
        count(distinct case when date_add(install_dt,interval 1 day) = event_date then player_id else null end) as retention
    from (
        select 
            player_id,
            event_date,
            min(event_date) over (partition by player_id) as install_dt
        from 
            Activity
    ) a 
    group by 
        install_dt
)
select 
    install_dt,
    installs,
    round(retention/installs,2) as Day1_retention
from 
    base 