-- -- -- -- -- -- -- -- -- -- # Write your MySQL query statement below
-- -- -- -- -- -- -- -- -- -- with base as (
-- -- -- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- -- -- --         distinct
-- -- -- -- -- -- -- -- -- --         user_id,
-- -- -- -- -- -- -- -- -- --         spend_date,
-- -- -- -- -- -- -- -- -- --         sum(case when platform in ('mobile','desktop') then 1 else 0 end) over (partition by user_id,spend_date) as is_both,
-- -- -- -- -- -- -- -- -- --         platform as plfm,
-- -- -- -- -- -- -- -- -- --         amount
-- -- -- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- -- -- --         Spending
-- -- -- -- -- -- -- -- -- -- ),
-- -- -- -- -- -- -- -- -- -- pairs as (
-- -- -- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- -- -- --         'desktop' as platform
-- -- -- -- -- -- -- -- -- --     union all
-- -- -- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- -- -- --         'mobile' as platform
-- -- -- -- -- -- -- -- -- --     union all
-- -- -- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- -- -- --         'both' as platform
-- -- -- -- -- -- -- -- -- -- ),
-- -- -- -- -- -- -- -- -- -- all_pairs as (
-- -- -- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- -- -- --         distinct
-- -- -- -- -- -- -- -- -- --         a.spend_date,
-- -- -- -- -- -- -- -- -- --         b.platform
-- -- -- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- -- -- --         Spending a 
-- -- -- -- -- -- -- -- -- --     cross join 
-- -- -- -- -- -- -- -- -- --         pairs b
-- -- -- -- -- -- -- -- -- -- )
-- -- -- -- -- -- -- -- -- -- ,final_info as (
-- -- -- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- -- -- --         spend_date,
-- -- -- -- -- -- -- -- -- --         case when is_both = 2 then 'both' else plfm end as platform,
-- -- -- -- -- -- -- -- -- --         sum(amount) as total_amount,
-- -- -- -- -- -- -- -- -- --         count(distinct user_id) as total_users
-- -- -- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- -- -- --         base
-- -- -- -- -- -- -- -- -- --     group by 
-- -- -- -- -- -- -- -- -- --         spend_date, platform
-- -- -- -- -- -- -- -- -- -- )
-- -- -- -- -- -- -- -- -- -- select 
-- -- -- -- -- -- -- -- -- --     a.spend_date,
-- -- -- -- -- -- -- -- -- --     a.platform,
-- -- -- -- -- -- -- -- -- --     ifnull(b.total_amount,0) as total_amount,
-- -- -- -- -- -- -- -- -- --     ifnull(b.total_users,0) as total_users
-- -- -- -- -- -- -- -- -- -- from 
-- -- -- -- -- -- -- -- -- --     all_pairs a
-- -- -- -- -- -- -- -- -- -- left join 
-- -- -- -- -- -- -- -- -- --     final_info b 
-- -- -- -- -- -- -- -- -- -- on 
-- -- -- -- -- -- -- -- -- --     a.spend_date = b.spend_date
-- -- -- -- -- -- -- -- -- --     and a.platform = b.platform
-- -- -- -- -- -- -- -- -- with base as (
-- -- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- -- --         'desktop' as platform
-- -- -- -- -- -- -- -- --     union all
-- -- -- -- -- -- -- -- --     select
-- -- -- -- -- -- -- -- --         'mobile' as platform
-- -- -- -- -- -- -- -- --     union all
-- -- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- -- --         'both' as platform
-- -- -- -- -- -- -- -- -- ),
-- -- -- -- -- -- -- -- -- filter_platform as (
-- -- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- -- --         spend_date,
-- -- -- -- -- -- -- -- --         user_id,
-- -- -- -- -- -- -- -- --         count(distinct platform) as platform_cnts
-- -- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- -- --         Spending b
-- -- -- -- -- -- -- -- --     group by 
-- -- -- -- -- -- -- -- --         spend_date, user_id
-- -- -- -- -- -- -- -- -- ),
-- -- -- -- -- -- -- -- -- final_info as (
-- -- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- -- --         spend_date,
-- -- -- -- -- -- -- -- --         user_id,
-- -- -- -- -- -- -- -- --         case when platform_cnts = 2 then 'both' 
-- -- -- -- -- -- -- -- --             else platform end as platform,
-- -- -- -- -- -- -- -- --         amount
-- -- -- -- -- -- -- -- --     from (
-- -- -- -- -- -- -- -- --         select 
-- -- -- -- -- -- -- -- --             a.user_id,
-- -- -- -- -- -- -- -- --             a.spend_date,
-- -- -- -- -- -- -- -- --             a.platform,
-- -- -- -- -- -- -- -- --             a.amount,
-- -- -- -- -- -- -- -- --             b.platform_cnts
-- -- -- -- -- -- -- -- --         from 
-- -- -- -- -- -- -- -- --             Spending a 
-- -- -- -- -- -- -- -- --         inner join 
-- -- -- -- -- -- -- -- --             filter_platform b
-- -- -- -- -- -- -- -- --         on 
-- -- -- -- -- -- -- -- --             a.spend_date = b.spend_date and a.user_id = b.user_id
-- -- -- -- -- -- -- -- --     ) a
-- -- -- -- -- -- -- -- -- ),
-- -- -- -- -- -- -- -- -- all_pairs as (
-- -- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- -- --         a.spend_date,
-- -- -- -- -- -- -- -- --         b.platform
-- -- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- -- --         Spending a 
-- -- -- -- -- -- -- -- --     cross join 
-- -- -- -- -- -- -- -- --         base b 
-- -- -- -- -- -- -- -- -- ),
-- -- -- -- -- -- -- -- -- last_info as (
-- -- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- -- --         spend_date,
-- -- -- -- -- -- -- -- --         platform,
-- -- -- -- -- -- -- -- --         sum(amount) as total_amount,
-- -- -- -- -- -- -- -- --         count(distinct user_id) as total_users
-- -- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- -- --         final_info
-- -- -- -- -- -- -- -- --     group by 
-- -- -- -- -- -- -- -- --         1,2
-- -- -- -- -- -- -- -- -- )
-- -- -- -- -- -- -- -- -- select 
-- -- -- -- -- -- -- -- --     distinct
-- -- -- -- -- -- -- -- --     a.spend_date,
-- -- -- -- -- -- -- -- --     a.platform,
-- -- -- -- -- -- -- -- --     ifnull(b.total_amount,0) as total_amount,
-- -- -- -- -- -- -- -- --     ifnull(b.total_users,0) as total_users
-- -- -- -- -- -- -- -- -- from 
-- -- -- -- -- -- -- -- --     all_pairs a 
-- -- -- -- -- -- -- -- -- left join 
-- -- -- -- -- -- -- -- --     last_info b 
-- -- -- -- -- -- -- -- -- on 
-- -- -- -- -- -- -- -- --     a.spend_date = b.spend_date and a.platform = b.platform
-- -- -- -- -- -- -- -- with base as (
-- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- --         distinct 
-- -- -- -- -- -- -- --         spend_date,
-- -- -- -- -- -- -- --         'both' as platform
-- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- --         Spending
-- -- -- -- -- -- -- --     union
-- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- --         distinct
-- -- -- -- -- -- -- --         spend_date,
-- -- -- -- -- -- -- --         'mobile' as platform
-- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- --         Spending
-- -- -- -- -- -- -- --     union
-- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- --         distinct
-- -- -- -- -- -- -- --         spend_date,
-- -- -- -- -- -- -- --         'desktop' as platform
-- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- --         Spending
-- -- -- -- -- -- -- -- ),
-- -- -- -- -- -- -- -- plats as (
-- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- --         spend_date,
-- -- -- -- -- -- -- --         user_id,
-- -- -- -- -- -- -- --         count(distinct platform) as platforms,
-- -- -- -- -- -- -- --         sum(amount) as total_amount
-- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- --         Spending a
-- -- -- -- -- -- -- --     where 
-- -- -- -- -- -- -- --         user_id
-- -- -- -- -- -- -- --     group by 
-- -- -- -- -- -- -- --         1,2
-- -- -- -- -- -- -- -- ),
-- -- -- -- -- -- -- -- final_info as (
-- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- --         distinct
-- -- -- -- -- -- -- --         a.spend_date,
-- -- -- -- -- -- -- --         a.user_id,
-- -- -- -- -- -- -- --         case when b.platforms = 2 then 'both' else a.platform end as platform,
-- -- -- -- -- -- -- --         b.platforms,
-- -- -- -- -- -- -- --         b.total_amount
-- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- --         Spending a 
-- -- -- -- -- -- -- --     inner join 
-- -- -- -- -- -- -- --         plats b 
-- -- -- -- -- -- -- --     on 
-- -- -- -- -- -- -- --         a.spend_date = b.spend_date and a.user_id = b.user_id
-- -- -- -- -- -- -- -- )
-- -- -- -- -- -- -- -- select 
-- -- -- -- -- -- -- --     a.spend_date,
-- -- -- -- -- -- -- --     a.platform,
-- -- -- -- -- -- -- --     ifnull(sum(b.total_amount),0) as total_amount,
-- -- -- -- -- -- -- --     count(distinct b.user_id) as total_users
-- -- -- -- -- -- -- -- from 
-- -- -- -- -- -- -- --     base a 
-- -- -- -- -- -- -- -- left join 
-- -- -- -- -- -- -- --     final_info b 
-- -- -- -- -- -- -- -- on 
-- -- -- -- -- -- -- --     a.spend_date = b.spend_date and a.platform = b.platform
-- -- -- -- -- -- -- -- group by 
-- -- -- -- -- -- -- --     a.spend_date, a.platform

-- -- -- -- -- -- -- with base as (
-- -- -- -- -- -- --     select 
-- -- -- -- -- -- --         distinct 
-- -- -- -- -- -- --         spend_date,
-- -- -- -- -- -- --         'mobile' as platform
-- -- -- -- -- -- --     from 
-- -- -- -- -- -- --         Spending
-- -- -- -- -- -- --     union all
-- -- -- -- -- -- --     select 
-- -- -- -- -- -- --         distinct 
-- -- -- -- -- -- --         spend_date,
-- -- -- -- -- -- --         'desktop' as platform
-- -- -- -- -- -- --     from 
-- -- -- -- -- -- --         Spending
-- -- -- -- -- -- --     union all
-- -- -- -- -- -- --     select 
-- -- -- -- -- -- --         distinct 
-- -- -- -- -- -- --         spend_date,
-- -- -- -- -- -- --         'both' as platform
-- -- -- -- -- -- --     from 
-- -- -- -- -- -- --         Spending
-- -- -- -- -- -- -- ),
-- -- -- -- -- -- -- platform_cte as (
-- -- -- -- -- -- --     select 
-- -- -- -- -- -- --         a.user_id,
-- -- -- -- -- -- --         a.spend_date,
-- -- -- -- -- -- --         case when b.platform_cnts = 2 then 'both' else a.platform end as platform,
-- -- -- -- -- -- --         a.amount
-- -- -- -- -- -- --     from 
-- -- -- -- -- -- --         Spending a 
-- -- -- -- -- -- --     inner join 
-- -- -- -- -- -- --     (
-- -- -- -- -- -- --         select 
-- -- -- -- -- -- --             user_id,
-- -- -- -- -- -- --             spend_date,
-- -- -- -- -- -- --             count(distinct platform) as platform_cnts
-- -- -- -- -- -- --         from 
-- -- -- -- -- -- --             Spending 
-- -- -- -- -- -- --         group by 
-- -- -- -- -- -- --             1,2
-- -- -- -- -- -- --     ) b
-- -- -- -- -- -- --     on 
-- -- -- -- -- -- --         a.user_id = b.user_id and a.spend_date = b.spend_date
-- -- -- -- -- -- -- )
-- -- -- -- -- -- -- select 
-- -- -- -- -- -- --     a.spend_date as spend_date,
-- -- -- -- -- -- --     a.platform as platform,
-- -- -- -- -- -- --     ifnull(sum(b.amount),0) as total_amount,
-- -- -- -- -- -- --     count(distinct b.user_id) as total_users
-- -- -- -- -- -- -- from 
-- -- -- -- -- -- --     base a 
-- -- -- -- -- -- -- left join
-- -- -- -- -- -- --     platform_cte b
-- -- -- -- -- -- -- on
-- -- -- -- -- -- --     a.spend_date = b.spend_date and a.platform = b.platform
-- -- -- -- -- -- -- group by 
-- -- -- -- -- -- --     spend_date,platform
-- -- -- -- -- -- with base as (
-- -- -- -- -- --     select 
-- -- -- -- -- --         spend_date,
-- -- -- -- -- --         'both' as platform
-- -- -- -- -- --     from 
-- -- -- -- -- --         Spending
-- -- -- -- -- --     union all
-- -- -- -- -- --     select 
-- -- -- -- -- --         spend_date,
-- -- -- -- -- --         'mobile' as platform
-- -- -- -- -- --     from 
-- -- -- -- -- --         Spending
-- -- -- -- -- --     union all
-- -- -- -- -- --     select
-- -- -- -- -- --         spend_date,
-- -- -- -- -- --         'desktop' as platform
-- -- -- -- -- --     from 
-- -- -- -- -- --         Spending
-- -- -- -- -- -- ),
-- -- -- -- -- -- platform_cte as (
-- -- -- -- -- --     select 
-- -- -- -- -- --         distinct
-- -- -- -- -- --         spend_date,
-- -- -- -- -- --         amount,
-- -- -- -- -- --         user_id,
-- -- -- -- -- --         case when platform_cnts = 2 then 'both' else platform end as platform
-- -- -- -- -- --     from (
-- -- -- -- -- --         select 
-- -- -- -- -- --             spend_date,
-- -- -- -- -- --             platform,
-- -- -- -- -- --             amount,
-- -- -- -- -- --             user_id,
-- -- -- -- -- --             count(platform) over (partition by spend_date,user_id) as platform_cnts
-- -- -- -- -- --         from 
-- -- -- -- -- --             Spending
-- -- -- -- -- --     ) a
-- -- -- -- -- -- )
-- -- -- -- -- -- select 
-- -- -- -- -- --     spend_date,
-- -- -- -- -- --     platform,
-- -- -- -- -- --     sum(total_amount) as total_amount,
-- -- -- -- -- --     count(distinct user_id) as total_users
-- -- -- -- -- -- from (
-- -- -- -- -- --     select 
-- -- -- -- -- --         distinct
-- -- -- -- -- --         a.spend_date,
-- -- -- -- -- --         a.platform,
-- -- -- -- -- --         ifnull(b.amount,0) as total_amount,
-- -- -- -- -- --         b.user_id
-- -- -- -- -- --     from 
-- -- -- -- -- --         base a 
-- -- -- -- -- --     left join 
-- -- -- -- -- --         platform_cte b 
-- -- -- -- -- --     on 
-- -- -- -- -- --         a.spend_date = b.spend_date and a.platform = b.platform
-- -- -- -- -- -- ) a
-- -- -- -- -- -- group by 
-- -- -- -- -- --     spend_date, platform

-- -- -- -- -- with base as (
-- -- -- -- --     select 
-- -- -- -- --         spend_date,
-- -- -- -- --         'both' as platform
-- -- -- -- --     from 
-- -- -- -- --         Spending
-- -- -- -- --     union all
-- -- -- -- --     select 
-- -- -- -- --         spend_date,
-- -- -- -- --         'mobile' as platform
-- -- -- -- --     from 
-- -- -- -- --         Spending
-- -- -- -- --     union all
-- -- -- -- --     select 
-- -- -- -- --         spend_date,
-- -- -- -- --         'desktop' as platform
-- -- -- -- --     from 
-- -- -- -- --         Spending
-- -- -- -- -- ),
-- -- -- -- -- spending_info as (
-- -- -- -- --     select 
-- -- -- -- --         spend_date,
-- -- -- -- --         platform,
-- -- -- -- --         sum(amount) as total_amount,
-- -- -- -- --         count(distinct user_id) as total_users
-- -- -- -- --     from (
-- -- -- -- --         select 
-- -- -- -- --             spend_date,
-- -- -- -- --             user_id,
-- -- -- -- --             amount,
-- -- -- -- --             case when count(user_id) over (partition by user_id,spend_date) = 2 then 'both'
-- -- -- -- --             else platform end as platform
-- -- -- -- --         from 
-- -- -- -- --             Spending
-- -- -- -- --     ) a 
-- -- -- -- --     group by 
-- -- -- -- --         spend_date, platform
-- -- -- -- -- )
-- -- -- -- -- select 
-- -- -- -- --     distinct 
-- -- -- -- --     a.spend_date,
-- -- -- -- --     a.platform,
-- -- -- -- --     ifnull(b.total_amount,0) as total_amount,
-- -- -- -- --     ifnull(b.total_users,0) as total_users
-- -- -- -- -- from 
-- -- -- -- --     base a 
-- -- -- -- -- left join 
-- -- -- -- --     spending_info b 
-- -- -- -- -- on
-- -- -- -- --     a.spend_date = b.spend_date and a.platform = b.platform

-- -- -- -- with base as (
-- -- -- --     select 
-- -- -- --         'both' as platform,
-- -- -- --         spend_date 
-- -- -- --     from 
-- -- -- --         Spending
-- -- -- --     union
-- -- -- --     select 
-- -- -- --         'mobile' as platform,
-- -- -- --         spend_date
-- -- -- --     from 
-- -- -- --         Spending
-- -- -- --     union
-- -- -- --     select 
-- -- -- --         'desktop' as platform,
-- -- -- --         spend_date
-- -- -- --     from 
-- -- -- --         Spending
-- -- -- -- ),
-- -- -- -- platform_info as (
-- -- -- --     select 
-- -- -- --         user_id,
-- -- -- --         spend_date,
-- -- -- --         case when cnts >= 2 then 'both' else platform end as platform,
-- -- -- --         amount
-- -- -- --     from (
-- -- -- --     select 
-- -- -- --         user_id,
-- -- -- --         spend_date,
-- -- -- --         platform,
-- -- -- --         amount,
-- -- -- --         count(user_id) over (partition by user_id,spend_date) as cnts
-- -- -- --     from 
-- -- -- --         Spending
-- -- -- --     ) a 
-- -- -- -- )
-- -- -- -- select 
-- -- -- --     a.spend_date as spend_date,
-- -- -- --     a.platform as platform,
-- -- -- --     sum(ifnull(b.amount,0)) as total_amount,
-- -- -- --     count(distinct b.user_id) as total_users
-- -- -- -- from 
-- -- -- --     base a 
-- -- -- -- left join 
-- -- -- --     platform_info b 
-- -- -- -- on 
-- -- -- --     a.spend_date = b.spend_date and a.platform = b.platform
-- -- -- -- group by 
-- -- -- --     spend_date, platform


-- -- -- with base as (
-- -- --     select 
-- -- --         'both' as platform,
-- -- --         spend_date
-- -- --     from 
-- -- --         Spending
-- -- --     union 
-- -- --     select 
-- -- --         'desktop' as platform,
-- -- --         spend_date
-- -- --     from 
-- -- --         Spending
-- -- --     union
-- -- --     select 
-- -- --         'mobile' as platform,
-- -- --         spend_date
-- -- --     from 
-- -- --         Spending
-- -- -- ),
-- -- -- filtered_info as (
-- -- --     select 
-- -- --         spend_date,
-- -- --         case when cnts = 2 then 'both' else platform end as platform,
-- -- --         amount,
-- -- --         user_id
-- -- --     from (
-- -- --         select 
-- -- --             spend_date,
-- -- --             user_id,
-- -- --             platform,
-- -- --             count(platform) over (partition by user_id,spend_date) as cnts,
-- -- --             amount
-- -- --         from 
-- -- --             Spending
-- -- --     ) a
-- -- -- )
-- -- -- select 
-- -- --     a.spend_date,
-- -- --     a.platform,
-- -- --     sum(coalesce(b.amount,0)) as total_amount,
-- -- --     count(distinct user_id) as total_users
-- -- -- from 
-- -- --     base a 
-- -- -- left join
-- -- --     filtered_info b 
-- -- -- on
-- -- --     a.spend_date = b.spend_date and a.platform = b.platform 
-- -- -- group by 
-- -- --     spend_date, platform 

-- -- with base as (
-- --     select 
-- --         'both' as platform,
-- --         spend_date
-- --     from 
-- --         Spending
-- --     union
-- --     select 
-- --         'desktop' as platform,
-- --         spend_date
-- --     from 
-- --         Spending
-- --     union 
-- --     select 
-- --         'mobile' as platform,
-- --         spend_date
-- --     from 
-- --         Spending
-- -- ),
-- -- final_info as (
-- --     select 
-- --         user_id,
-- --         spend_date,
-- --         max(case when cnts = 2 then 'both' else platform end) as platform,
-- --         sum(amount) as total_amount
-- --     from (
-- --         select 
-- --             user_id,
-- --             spend_date,
-- --             platform,
-- --             count(platform) over (partition by spend_date,user_id) as cnts,
-- --             amount
-- --         from 
-- --             Spending
-- --     ) a
-- --     group by 
-- --         1,2
-- -- )
-- -- select 
-- --     a.spend_date,
-- --     a.platform,
-- --     coalesce(sum(b.total_amount),0) as total_amount,
-- --     count(distinct b.user_id) as total_users
-- -- from 
-- --     base a 
-- -- left join 
-- --     final_info b 
-- -- on 
-- --     a.spend_date = b.spend_date and a.platform = b.platform
-- -- group by 
-- --     a.spend_date, a.platform
-- with recursive cte as (
--     select 
--         'both' as platform,
--         spend_date
--     from
--         Spending
--     union 
--     select 
--         'mobile' as platform,
--         spend_date
--     from 
--         Spending
--     union
--     select
--         'desktop' as platform,
--         spend_date
--     from 
--         Spending 
-- ),
-- final_info as (
--     select 
--         distinct 
--         a.user_id,
--         a.spend_date,
--         sum(a.amount) over (partition by a.user_id,a.spend_date) as amount,
--         case when b.platform_cnts = 2 then 'both' else a.platform end as platform
--     from 
--         Spending a 
--     inner join (
--         select 
--             user_id,
--             spend_date,
--             count(distinct platform) as platform_cnts
--         from 
--             Spending 
--         group by 
--             user_id, spend_date
--     ) b 
--     on 
--         a.user_id = b.user_id and a.spend_date = b.spend_date
-- )
-- select 
--     a.spend_date,
--     a.platform,
--     sum(coalesce(b.amount,0)) as total_amount,
--     count(distinct b.user_id) as total_users
-- from 
--     cte a 
-- left join 
--     final_info b 
-- on 
--     a.spend_date = b.spend_date and a.platform = b.platform
-- group by 
--     a.spend_date, a.platform
with recursive cte as (
    select 
        'both' as platform,
        spend_date
    from 
        Spending
    union 
    select 
        'mobile' as platform,
        spend_date
    from 
        Spending
    union
    select 
        'desktop' as platform,
        spend_date
    from 
        Spending
),
final_info as (
    select 
        distinct 
        user_id,
        spend_date,
        case when platform_cnts = 2 then 'both' else platform end as platform,
        total_amount
    from (
        select
            user_id,
            spend_date,
            platform,
            count(platform) over (partition by user_id,spend_date) as platform_cnts,
            sum(amount) over (partition by user_id,spend_date) as total_amount
        from 
            Spending
    ) a 
)
select 
    a.spend_date,
    a.platform,
    sum(coalesce(b.total_amount,0)) as total_amount,
    count(distinct b.user_id) as total_users
from 
    cte a 
left join 
    final_info b 
on 
    a.spend_date = b.spend_date and a.platform = b.platform
group by 
    a.spend_date, a.platform
