
-- -- -- -- -- -- -- -- -- -- -- -- # Write your MySQL query statement below
-- -- -- -- -- -- -- -- -- -- -- -- with base as (
-- -- -- -- -- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- -- -- -- -- --         a.item_id,
-- -- -- -- -- -- -- -- -- -- -- --         a.item_category,
-- -- -- -- -- -- -- -- -- -- -- --         ifnull(b.quantity,0) as quantity,
-- -- -- -- -- -- -- -- -- -- -- --         ifnull(weekday(b.order_date),0) as order_date
-- -- -- -- -- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- -- -- -- -- --         Items a 
-- -- -- -- -- -- -- -- -- -- -- --     left join 
-- -- -- -- -- -- -- -- -- -- -- --         Orders b 
-- -- -- -- -- -- -- -- -- -- -- --     on 
-- -- -- -- -- -- -- -- -- -- -- --         a.item_id = b.item_id
-- -- -- -- -- -- -- -- -- -- -- -- )
-- -- -- -- -- -- -- -- -- -- -- -- select 
-- -- -- -- -- -- -- -- -- -- -- --     item_category as Category,
-- -- -- -- -- -- -- -- -- -- -- --     sum(case when order_date = 0 then quantity else 0 end) as Monday,
-- -- -- -- -- -- -- -- -- -- -- --     sum(case when order_date = 1 then quantity else 0 end) as Tuesday,
-- -- -- -- -- -- -- -- -- -- -- --     sum(case when order_date = 2 then quantity else 0 end) as Wednesday,
-- -- -- -- -- -- -- -- -- -- -- --     sum(case when order_date = 3 then quantity else 0 end) as Thursday,
-- -- -- -- -- -- -- -- -- -- -- --     sum(case when order_date = 4 then quantity else 0 end) as Friday,
-- -- -- -- -- -- -- -- -- -- -- --     sum(case when order_date = 5 then quantity else 0 end) as Saturday,
-- -- -- -- -- -- -- -- -- -- -- --     sum(case when order_date = 6 then quantity else 0 end) as Sunday
-- -- -- -- -- -- -- -- -- -- -- -- from 
-- -- -- -- -- -- -- -- -- -- -- --     base 
-- -- -- -- -- -- -- -- -- -- -- -- group by 
-- -- -- -- -- -- -- -- -- -- -- --     Category
-- -- -- -- -- -- -- -- -- -- -- -- order by 
-- -- -- -- -- -- -- -- -- -- -- --     Category asc

-- -- -- -- -- -- -- -- -- -- -- with base as (
-- -- -- -- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- -- -- -- --         a.item_id,
-- -- -- -- -- -- -- -- -- -- --         a.item_category as category,
-- -- -- -- -- -- -- -- -- -- --         b.order_id,
-- -- -- -- -- -- -- -- -- -- --         b.order_date,
-- -- -- -- -- -- -- -- -- -- --         weekday(b.order_date) as days,
-- -- -- -- -- -- -- -- -- -- --         ifnull(b.quantity,0) as quantity
-- -- -- -- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- -- -- -- --         Items a 
-- -- -- -- -- -- -- -- -- -- --     left join 
-- -- -- -- -- -- -- -- -- -- --         Orders b 
-- -- -- -- -- -- -- -- -- -- --     on 
-- -- -- -- -- -- -- -- -- -- --         a.item_id = b.item_id
-- -- -- -- -- -- -- -- -- -- -- )
-- -- -- -- -- -- -- -- -- -- -- select 
-- -- -- -- -- -- -- -- -- -- --     category,
-- -- -- -- -- -- -- -- -- -- --     sum(case when days = 0 then quantity else 0 end) as Monday,
-- -- -- -- -- -- -- -- -- -- --     sum(case when days = 1 then quantity else 0 end) as Tuesday,
-- -- -- -- -- -- -- -- -- -- --     sum(case when days = 2 then quantity else 0 end) as Wednesday,
-- -- -- -- -- -- -- -- -- -- --     sum(case when days = 3 then quantity else 0 end) as Thursday,
-- -- -- -- -- -- -- -- -- -- --     sum(case when days = 4 then quantity else 0 end) as Friday,
-- -- -- -- -- -- -- -- -- -- --     sum(case when days = 5 then quantity else 0 end) as Saturday,
-- -- -- -- -- -- -- -- -- -- --     sum(case when days = 6 then quantity else 0 end) as Sunday
-- -- -- -- -- -- -- -- -- -- -- from 
-- -- -- -- -- -- -- -- -- -- --     base 
-- -- -- -- -- -- -- -- -- -- -- group by 
-- -- -- -- -- -- -- -- -- -- --     category
-- -- -- -- -- -- -- -- -- -- -- order by 
-- -- -- -- -- -- -- -- -- -- --     category
-- -- -- -- -- -- -- -- -- -- with base as (
-- -- -- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- -- -- --         a.item_category as category,
-- -- -- -- -- -- -- -- -- --         weekday(ifnull(b.order_date,0)) as days,
-- -- -- -- -- -- -- -- -- --         sum(ifnull(b.quantity,0)) as quantity
-- -- -- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- -- -- --         Items a
-- -- -- -- -- -- -- -- -- --     left join 
-- -- -- -- -- -- -- -- -- --         Orders b
-- -- -- -- -- -- -- -- -- --     on 
-- -- -- -- -- -- -- -- -- --         a.item_id = b.item_id
-- -- -- -- -- -- -- -- -- --     group by 
-- -- -- -- -- -- -- -- -- --         category,days
-- -- -- -- -- -- -- -- -- -- )
-- -- -- -- -- -- -- -- -- -- select 
-- -- -- -- -- -- -- -- -- --     category,
-- -- -- -- -- -- -- -- -- --     sum(case when days = 0 then quantity else 0 end) as Monday,
-- -- -- -- -- -- -- -- -- --     sum(case when days = 1 then quantity else 0 end) as Tuesday,
-- -- -- -- -- -- -- -- -- --     sum(case when days = 2 then quantity else 0 end) as Wednesday,
-- -- -- -- -- -- -- -- -- --     sum(case when days = 3 then quantity else 0 end) as Thursday,
-- -- -- -- -- -- -- -- -- --     sum(case when days = 4 then quantity else 0 end) as Friday,
-- -- -- -- -- -- -- -- -- --     sum(case when days = 5 then quantity else 0 end) as Saturday,
-- -- -- -- -- -- -- -- -- --     sum(case when days = 6 then quantity else 0 end) as Sunday
-- -- -- -- -- -- -- -- -- -- from 
-- -- -- -- -- -- -- -- -- --     base 
-- -- -- -- -- -- -- -- -- -- group by 
-- -- -- -- -- -- -- -- -- --     category 
-- -- -- -- -- -- -- -- -- -- order by 
-- -- -- -- -- -- -- -- -- --     category
-- -- -- -- -- -- -- -- -- with base as (
-- -- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- -- --         a.item_category as category,
-- -- -- -- -- -- -- -- --         weekday(b.order_date) as days,
-- -- -- -- -- -- -- -- --         ifnull(sum(b.quantity),0) as quantity
-- -- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- -- --         Items a 
-- -- -- -- -- -- -- -- --     left join
-- -- -- -- -- -- -- -- --         Orders b 
-- -- -- -- -- -- -- -- --     on 
-- -- -- -- -- -- -- -- --         a.item_id = b.item_id
-- -- -- -- -- -- -- -- --     group by 
-- -- -- -- -- -- -- -- --         category,days
-- -- -- -- -- -- -- -- -- )
-- -- -- -- -- -- -- -- -- select 
-- -- -- -- -- -- -- -- --     category,
-- -- -- -- -- -- -- -- --     sum(case when days = 0 then quantity else 0 end) as Monday,
-- -- -- -- -- -- -- -- --     sum(case when days = 1 then quantity else 0 end) as Tuesday,
-- -- -- -- -- -- -- -- --     sum(case when days = 2 then quantity else 0 end) as Wednesday,
-- -- -- -- -- -- -- -- --     sum(case when days = 3 then quantity else 0 end) as Thursday,
-- -- -- -- -- -- -- -- --     sum(case when days = 4 then quantity else 0 end) as Friday,
-- -- -- -- -- -- -- -- --     sum(case when days = 5 then quantity else 0 end) as Saturday,
-- -- -- -- -- -- -- -- --     sum(case when days = 6 then quantity else 0 end) as Sunday
-- -- -- -- -- -- -- -- -- from 
-- -- -- -- -- -- -- -- --     base
-- -- -- -- -- -- -- -- -- group by 
-- -- -- -- -- -- -- -- --     category
-- -- -- -- -- -- -- -- -- order by 
-- -- -- -- -- -- -- -- --     category

-- -- -- -- -- -- -- -- with base as (
-- -- -- -- -- -- -- --     select 
-- -- -- -- -- -- -- --         a.item_category as Category,
-- -- -- -- -- -- -- --         weekday(b.order_date) as days,
-- -- -- -- -- -- -- --         sum(ifnull(b.quantity,0)) as quantity
-- -- -- -- -- -- -- --     from 
-- -- -- -- -- -- -- --         Items a
-- -- -- -- -- -- -- --     left join 
-- -- -- -- -- -- -- --         Orders b 
-- -- -- -- -- -- -- --     on 
-- -- -- -- -- -- -- --         a.item_id = b.item_id
-- -- -- -- -- -- -- --     group by 
-- -- -- -- -- -- -- --         Category, days
-- -- -- -- -- -- -- -- )
-- -- -- -- -- -- -- -- select 
-- -- -- -- -- -- -- --     Category,
-- -- -- -- -- -- -- --     sum(case when days = 0 then quantity else 0 end) as Monday,
-- -- -- -- -- -- -- --     sum(case when days = 1 then quantity else 0 end) as Tuesday,
-- -- -- -- -- -- -- --     sum(case when days = 2 then quantity else 0 end) as Wednesday,
-- -- -- -- -- -- -- --     sum(case when days = 3 then quantity else 0 end) as Thursday,
-- -- -- -- -- -- -- --     sum(case when days = 4 then quantity else 0 end) as Friday,
-- -- -- -- -- -- -- --     sum(case when days = 5 then quantity else 0 end) as Saturday,
-- -- -- -- -- -- -- --     sum(case when days = 6 then quantity else 0 end) as Sunday
-- -- -- -- -- -- -- -- from 
-- -- -- -- -- -- -- --     base 
-- -- -- -- -- -- -- -- group by 
-- -- -- -- -- -- -- --     Category
-- -- -- -- -- -- -- -- order by 
-- -- -- -- -- -- -- --     Category
-- -- -- -- -- -- -- with base as (
-- -- -- -- -- -- --     select 
-- -- -- -- -- -- --         a.item_category,
-- -- -- -- -- -- --         b.order_date,
-- -- -- -- -- -- --         b.quantity
-- -- -- -- -- -- --     from 
-- -- -- -- -- -- --         Items a 
-- -- -- -- -- -- --     left join 
-- -- -- -- -- -- --         Orders b 
-- -- -- -- -- -- --     on 
-- -- -- -- -- -- --         a.item_id = b.item_id
-- -- -- -- -- -- -- )
-- -- -- -- -- -- -- select 
-- -- -- -- -- -- --     item_category as Category,
-- -- -- -- -- -- --     max(case when dates = 0 then quantity else 0 end) as Monday,
-- -- -- -- -- -- --     max(case when dates = 1 then quantity else 0 end) as Tuesday,
-- -- -- -- -- -- --     max(case when dates = 2 then quantity else 0 end) as Wednesday,
-- -- -- -- -- -- --     max(case when dates = 3 then quantity else 0 end) as Thursday,
-- -- -- -- -- -- --     max(case when dates = 4 then quantity else 0 end) as Friday,
-- -- -- -- -- -- --     max(case when dates = 5 then quantity else 0 end) as Saturday,
-- -- -- -- -- -- --     max(case when dates = 6 then quantity else 0 end) as Sunday
-- -- -- -- -- -- -- from (
-- -- -- -- -- -- --     select 
-- -- -- -- -- -- --         item_category,
-- -- -- -- -- -- --         weekday(order_date) as dates,
-- -- -- -- -- -- --         sum(quantity) as quantity
-- -- -- -- -- -- --     from 
-- -- -- -- -- -- --         base 
-- -- -- -- -- -- --     group by 
-- -- -- -- -- -- --         item_category, dates
-- -- -- -- -- -- -- ) a
-- -- -- -- -- -- -- group by 
-- -- -- -- -- -- --     Category
-- -- -- -- -- -- -- order by 
-- -- -- -- -- -- --     Category
-- -- -- -- -- -- with base as (
-- -- -- -- -- --     select 
-- -- -- -- -- --         i.item_category as category,
-- -- -- -- -- --         weekday(o.order_date) as dates,
-- -- -- -- -- --         sum(ifnull(o.quantity,0)) as quantity
-- -- -- -- -- --     from 
-- -- -- -- -- --         Items i
-- -- -- -- -- --     left join 
-- -- -- -- -- --         Orders o
-- -- -- -- -- --     on 
-- -- -- -- -- --         i.item_id = o.item_id
-- -- -- -- -- --     group by 
-- -- -- -- -- --         category,dates
-- -- -- -- -- -- )
-- -- -- -- -- -- select 
-- -- -- -- -- --     category as category,
-- -- -- -- -- --     sum(if(dates = 0,quantity,0)) as Monday,
-- -- -- -- -- --     sum(if(dates = 1,quantity,0)) as Tuesday,
-- -- -- -- -- --     sum(if(dates = 2,quantity,0)) as Wednesday,
-- -- -- -- -- --     sum(if(dates = 3,quantity,0)) as Thursday,
-- -- -- -- -- --     sum(if(dates = 4,quantity,0)) as Friday,
-- -- -- -- -- --     sum(if(dates = 5,quantity,0)) as Saturday,
-- -- -- -- -- --     sum(if(dates = 6,quantity,0)) as Sunday
-- -- -- -- -- -- from 
-- -- -- -- -- --     base
-- -- -- -- -- -- group by 
-- -- -- -- -- --     category
-- -- -- -- -- -- order by 
-- -- -- -- -- --     category
-- -- -- -- -- with base as (
-- -- -- -- --     select 
-- -- -- -- --         weekday(o.order_date) as days,
-- -- -- -- --         i.item_category as Category,
-- -- -- -- --         sum(ifnull(o.quantity,0)) as quantity
-- -- -- -- --     from 
-- -- -- -- --         Orders o
-- -- -- -- --     right join 
-- -- -- -- --         Items i 
-- -- -- -- --     on 
-- -- -- -- --         o.item_id = i.item_id
-- -- -- -- --     group by
-- -- -- -- --         days, Category
-- -- -- -- -- )
-- -- -- -- -- select 
-- -- -- -- --     Category as CATEGORY,
-- -- -- -- --     sum(case when days = 0 then quantity else 0 end) as MONDAY,
-- -- -- -- --     sum(case when days = 1 then quantity else 0 end) as TUESDAY,
-- -- -- -- --     sum(case when days = 2 then quantity else 0 end) as WEDNESDAY,
-- -- -- -- --     sum(case when days = 3 then quantity else 0 end) as THURSDAY,
-- -- -- -- --     sum(case when days = 4 then quantity else 0 end) as FRIDAY,
-- -- -- -- --     sum(case when days = 5 then quantity else 0 end) as SATURDAY,
-- -- -- -- --     sum(case when days = 6 then quantity else 0 end) as SUNDAY
-- -- -- -- -- from 
-- -- -- -- --     base 
-- -- -- -- -- group by 
-- -- -- -- --     Category
-- -- -- -- -- order by 
-- -- -- -- --     Category 
-- -- -- -- select 
-- -- -- --     item_category as Category,
-- -- -- --     sum(case when days = 0 then quantity else 0 end) as Monday,
-- -- -- --     sum(case when days = 1 then quantity else 0 end) as Tuesday,
-- -- -- --     sum(case when days = 2 then quantity else 0 end) as Wednesday,
-- -- -- --     sum(case when days = 3 then quantity else 0 end) as Thursday,
-- -- -- --     sum(case when days = 4 then quantity else 0 end) as Friday,
-- -- -- --     sum(case when days = 5 then quantity else 0 end) as Saturday,
-- -- -- --     sum(case when days = 6 then quantity else 0 end) as Sunday
-- -- -- -- from (
-- -- -- --     select 
-- -- -- --         a.item_category,
-- -- -- --         weekday(b.order_date) as days,
-- -- -- --         sum(ifnull(b.quantity,0)) as quantity
-- -- -- --     from 
-- -- -- --         Items a 
-- -- -- --     left join 
-- -- -- --         Orders b 
-- -- -- --     on 
-- -- -- --         a.item_id = b.item_id 
-- -- -- --     group by 
-- -- -- --         a.item_category, days
-- -- -- -- ) a
-- -- -- -- group by 
-- -- -- --     category
-- -- -- -- order by 
-- -- -- --     category 
-- -- -- with base as (
-- -- --     select 
-- -- --         weekday(a.order_date) as days,
-- -- --         b.item_category as Category,
-- -- --         sum(ifnull(a.quantity,0)) as quantity
-- -- --     from 
-- -- --         Orders a 
-- -- --     right join 
-- -- --         Items b 
-- -- --     on 
-- -- --         a.item_id = b.item_id 
-- -- --     group by 
-- -- --         days,Category
-- -- -- )
-- -- -- select 
-- -- --     Category,
-- -- --     sum(case when days = 0 then quantity else 0 end) as Monday,
-- -- --     sum(case when days = 1 then quantity else 0 end) as Tuesday,
-- -- --     sum(case when days = 2 then quantity else 0 end) as Wednesday,
-- -- --     sum(case when days = 3 then quantity else 0 end) as Thursday,
-- -- --     sum(case when days = 4 then quantity else 0 end) as Friday,
-- -- --     sum(case when days = 5 then quantity else 0 end) as Saturday,
-- -- --     sum(case when days = 6 then quantity else 0 end) as Sunday
-- -- -- from 
-- -- --     base 
-- -- -- group by 
-- -- --     Category 
-- -- -- order by 
-- -- --     Category
-- -- with base as (
-- --     select 
-- --         a.item_category as Category,
-- --         weekday(b.order_date) as dates,
-- --         sum(coalesce(b.quantity,0)) as quantity
-- --     from 
-- --         Items a 
-- --     left join 
-- --         Orders b 
-- --     on 
-- --         a.item_id = b.item_id
-- --     group by 
-- --         Category, dates
-- -- )
-- -- select 
-- --     Category,
-- --     max(case when dates = 0 then quantity else 0 end) as Monday,
-- --     max(case when dates = 1 then quantity else 0 end) as Tuesday,
-- --     max(case when dates = 2 then quantity else 0 end) as Wednesday,
-- --     max(case when dates = 3 then quantity else 0 end) as Thursday,
-- --     max(case when dates = 4 then quantity else 0 end) as Friday,
-- --     max(case when dates = 5 then quantity else 0 end) as Saturday,
-- --     max(case when dates = 6 then quantity else 0 end) as Sunday
-- -- from 
-- --     base 
-- -- group by 
-- --     Category 
-- -- order by 
-- --     Category
-- with base as (
--     select 
--         weekday(b.order_date) as days,
--         a.item_category as Category,
--         sum(coalesce(b.quantity,0)) as quantity
--     from 
--         Items a 
--     left join 
--         Orders b 
--     on 
--         a.item_id = b.item_id
--     group by 
--         days, Category
-- )
-- select 
--     Category,
--     max(case when days = 0 then quantity else 0 end) as Monday,
--     max(case when days = 1 then quantity else 0 end) as Tuesday,
--     max(case when days = 2 then quantity else 0 end) as Wednesday,
--     max(case when days = 3 then quantity else 0 end) as Thursday,
--     max(case when days = 4 then quantity else 0 end) as Friday,
--     max(case when days = 5 then quantity else 0 end) as Saturday,
--     max(case when days = 6 then quantity else 0 end) as Sunday
-- from 
--     base 
-- group by 
--     Category 
-- order by 
--     Category
select 
    CATEGORY,
    max(case when days = 0 then quantity else 0 end) as MONDAY,
    max(case when days = 1 then quantity else 0 end) as TUESDAY,
    max(case when days = 2 then quantity else 0 end) as WEDNESDAY,
    max(case when days = 3 then quantity else 0 end) as THURSDAY,
    max(case when days = 4 then quantity else 0 end) as FRIDAY,
    max(case when days = 5 then quantity else 0 end) as SATURDAY,
    max(case when days = 6 then quantity else 0 end) as SUNDAY
from (
    select 
        a.item_category as Category,
        weekday(b.order_date) as days,
        sum(coalesce(b.quantity,0)) as quantity
    from 
        Items a 
    left join 
        Orders b 
    on 
        a.item_id = b.item_id 
    group by 
        Category, days
) a 
group by 
    Category
order by 
    Category 